// Timeline data: Geonim, Rishonim, Acharonim — with books, regions, Wikipedia
// links, and world events.
// Dates are CE (secular). Hebrew years are derived as CE + 3760 (approx.; the
// civil/Hebrew year overlap means ±1 near Rosh Hashanah). Some early dates are
// approximate ("circa") per the historical sources.
// `w` = Hebrew Wikipedia article title (used to build a he.wikipedia.org link).

const ERAS = {
  tannaim:   { he: "תנאים",   en: "Tannaim",   color: "#be123c" },
  amoraim:   { he: "אמוראים", en: "Amoraim",   color: "#7c3aed" },
  geonim:    { he: "גאונים",  en: "Geonim",    color: "#b45309" },
  rishonim:  { he: "ראשונים", en: "Rishonim",  color: "#1d4ed8" },
  acharonim: { he: "אחרונים", en: "Acharonim", color: "#047857" },
  chassidut: { he: "גדולי החסידות", en: "Chassidic masters", color: "#db2777" },
};

// Centers of Torah, each with a marker colour and a position (mx,my) on the
// schematic map (viewBox 320×240) — surfaces the geographic story.
const REGIONS = {
  bavel:         { he: "בבל",          en: "Babylonia",     color: "#a16207", mx: 258.8, my: 159 },
  sefarad:       { he: "ספרד",         en: "Spain",         color: "#ca8a04", mx: 38.1,  my: 118.8 },
  tzarfat:       { he: "צרפת",         en: "France",        color: "#2563eb", mx: 73.9,  my: 70.2 },
  ashkenaz:      { he: "אשכנז",        en: "Germany",       color: "#4f46e5", mx: 93.2,  my: 60.1 },
  provans:       { he: "פרובנס",       en: "Provence",      color: "#0d9488", mx: 75.2,  my: 97.2 },
  italia:        { he: "איטליה",       en: "Italy",         color: "#65a30d", mx: 112.6, my: 108.6 },
  tzfonAfrica:   { he: "צפון אפריקה",  en: "North Africa",  color: "#dc2626", mx: 101.6, my: 145.8 },
  eretzIsrael:   { he: "ארץ ישראל",    en: "Land of Israel",color: "#0891b2", mx: 216.9, my: 169.2 },
  turkiya:       { he: "תורכיה",        en: "Turkey",        color: "#c026d3", mx: 181,   my: 129 },
  mizrachEurope: { he: "מזרח אירופה",  en: "Eastern Europe",color: "#9333ea", mx: 162.2, my: 45 },
  merkazEurope:  { he: "מרכז אירופה",  en: "Central Europe",color: "#ea580c", mx: 131.5, my: 64.8 },
  iraq:          { he: "בבל (עיראק)",  en: "Iraq",          color: "#92400e", mx: 274.9, my: 177 },
  usa:           { he: "ארצות הברית",  en: "United States", color: "#475569", mx: 14,    my: 115.8, off: true },
};

// Migration of the Torah center from Bavel westward (~942–1088 CE).
// Paths are cubic Béziers in the map's 285×252 coordinate space.
const MIGRATION = [
  { d: "M258.8,159 C 196,204 80,178 41,121",  he: "בבל ← צפון אפריקה ← ספרד" },
  { d: "M258.8,159 C 198,112 150,78 95,62",   he: "בבל ← איטליה ← אשכנז" },
];

// Each figure: born/died in CE. `circa` flags approximate dates.
const FIGURES = [
  // ---------- TANNAIM (Mishnah era) ----------
  {
    era: "tannaim", he: "רבן גמליאל הזקן", en: "Rabban Gamliel the Elder",
    born: 1, died: 52, circa: true, region: "eretzIsrael", place: "ירושלים, ארץ ישראל",
    w: "רבן גמליאל הזקן", note: "נשיא הסנהדרין בירושלים בדור שלפני החורבן; נכדו של הלל הזקן.",
    books: [],
  },
  {
    era: "tannaim", he: "רבן יוחנן בן זכאי", en: "Rabban Yochanan ben Zakkai",
    born: 1, died: 90, circa: true, region: "eretzIsrael", place: "יבנה, ארץ ישראל",
    w: "רבן יוחנן בן זכאי", note: "ייסד את ישיבת יבנה לאחר החורבן והציל את התורה — 'תן לי יבנה וחכמיה'.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי צדוק (הכהן)", en: "Rabbi Zadok (the Tanna)",
    born: 1, died: 80, circa: true, region: "eretzIsrael", place: "ירושלים → יבנה",
    w: "רבי צדוק", note: "כהן ותנא בדור החורבן; התענה ארבעים שנה כדי שלא ייחרב הבית, ורבן יוחנן בן זכאי ביקש מאספסיאנוס לרפאותו.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי חנינא בן דוסא", en: "Rabbi Chanina ben Dosa",
    born: 10, died: 70, circa: true, region: "eretzIsrael", place: "ארב, גליל",
    w: "רבי חנינא בן דוסא", note: "מ'אנשי המעשה'; נודע בתפילותיו ובמופתיו ובחסידותו.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי נחוניה בן הקנה", en: "Rabbi Nehunya ben HaKanah",
    born: 10, died: 90, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי נחוניה בן הקנה", note: "תנא בדור החורבן ורבו של ר' ישמעאל; נודע בתפילתו בכניסה וביציאה מבית המדרש, והמסורת מייחסת לו את \"אנא בכח\".",
    books: [],
  },
  {
    era: "tannaim", he: "רבן גמליאל דיבנה", en: "Rabban Gamliel of Yavne",
    born: 50, died: 120, circa: true, region: "eretzIsrael", place: "יבנה, ארץ ישראל",
    w: "רבן גמליאל דיבנה", note: "נשיא הסנהדרין ביבנה; ביסס את מרכז התורה לאחר החורבן.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי אליעזר בן הורקנוס", en: "Rabbi Eliezer ben Hyrcanus",
    born: 40, died: 120, circa: true, region: "eretzIsrael", place: "לוד, ארץ ישראל",
    w: "רבי אליעזר בן הורקנוס", note: "מתלמידי רבן יוחנן בן זכאי ורבו של ר' עקיבא; 'בור סוד שאינו מאבד טיפה'.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יהושע (בן חנניה)", en: "Rabbi Yehoshua (ben Chananya)",
    born: 40, died: 130, circa: true, region: "eretzIsrael", place: "פקיעין, ארץ ישראל",
    w: "רבי יהושע בן חנניה", note: "מתלמידי רבן יוחנן בן זכאי; לוי וחכם, חברו של ר' אליעזר.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי אלעזר בן ערך", en: "Rabbi Elazar ben Arach",
    born: 40, died: 110, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי אלעזר בן ערך", note: "מחמשת תלמידי רבן יוחנן בן זכאי; \"כמעיין המתגבר\", ומופלא בדרשות מעשה מרכבה.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי אלעזר בן עזריה", en: "Rabbi Elazar ben Azaria",
    born: 50, died: 120, circa: true, region: "eretzIsrael", place: "יבנה, ארץ ישראל",
    w: "רבי אלעזר בן עזריה", note: "כהן ועשיר; נתמנה נשיא הסנהדרין ביבנה בצעירותו — 'הרי אני כבן שבעים שנה'.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי עקיבא", en: "Rabbi Akiva",
    born: 50, died: 135, circa: true, region: "eretzIsrael", place: "בני ברק, ארץ ישראל",
    w: "רבי עקיבא", note: "מגדולי התנאים; סידר את ההלכה. נהרג על קידוש השם בימי אדריאנוס.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יהודה בן בבא", en: "Rabbi Yehuda ben Bava",
    born: 50, died: 135, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי יהודה בן בבא", note: "מחכמי יבנה; נהרג על קידוש השם בגזרות אדריאנוס לאחר שסמך את תלמידי ר' עקיבא וקיים את שלשלת הסמיכה.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי ישמעאל", en: "Rabbi Yishmael",
    born: 90, died: 135, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי ישמעאל", note: "בר הפלוגתא של ר' עקיבא; שלוש עשרה המידות שהתורה נדרשת בהן.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי טרפון", en: "Rabbi Tarfon",
    born: 50, died: 130, circa: true, region: "eretzIsrael", place: "לוד, ארץ ישראל",
    w: "רבי טרפון", note: "מחכמי יבנה; כהן ובר-פלוגתא של ר' עקיבא.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יוסי הגלילי", en: "Rabbi Yossi HaGlili",
    born: 80, died: 130, circa: true, region: "eretzIsrael", place: "הגליל, ארץ ישראל",
    w: "רבי יוסי הגלילי", note: "מחכמי יבנה; בר-פלוגתא של ר' עקיבא ור' טרפון.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יוחנן בן נורי", en: "Rabbi Yochanan ben Nuri",
    born: 70, died: 140, circa: true, region: "eretzIsrael", place: "יבנה, ארץ ישראל",
    w: "רבי יוחנן בן נורי", note: "מחכמי יבנה; חברו ובר-פלוגתו של ר' עקיבא, ונודע בבקיאותו העצומה.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי מאיר", en: "Rabbi Meir",
    born: 110, died: 170, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי מאיר", note: "מתלמידי ר' עקיבא; 'סתם משנה ר' מאיר'.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יהודה בר עילאי", en: "Rabbi Yehuda bar Ilai",
    born: 100, died: 170, circa: true, region: "eretzIsrael", place: "אושא, ארץ ישראל",
    w: "רבי יהודה", note: "מתלמידי ר' עקיבא; 'ראש המדברים בכל מקום'.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יוסי בן קיסמא", en: "Rabbi Yossi ben Kisma",
    born: 80, died: 135, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי יוסי בן קיסמא", note: "תנא; נודע במאמרו 'איני דר אלא במקום תורה'.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יוחנן הסנדלר", en: "Rabbi Yochanan HaSandlar",
    born: 100, died: 170, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי יוחנן הסנדלר", note: "מתלמידי ר' עקיבא; חכם ובעל מלאכה.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי שמעון בר יוחאי (רשב\"י)", en: "Rabbi Shimon bar Yochai",
    born: 100, died: 160, circa: true, region: "eretzIsrael", place: "מירון, ארץ ישראל",
    w: "רבי שמעון בר יוחאי", note: "מתלמידי ר' עקיבא; על פי המסורת מחבר ספר הזוהר.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי נתן (הבבלי)", en: "Rabbi Nathan (the Babylonian)",
    born: 110, died: 180, circa: true, region: "eretzIsrael", place: "בבל → ארץ ישראל",
    w: "רבי נתן", note: "בנו של ראש הגולה שעלה לארץ וכיהן כאב בית הדין בסנהדרין; שמו נישא בחיבור \"אבות דרבי נתן\".",
    books: [],
  },
  {
    era: "tannaim", he: "רבי יהודה הנשיא (רבי)", en: "Rabbi Yehuda HaNasi",
    born: 135, died: 217, circa: true, region: "eretzIsrael", place: "בית שערים → ציפורי",
    w: "רבי יהודה הנשיא", note: "עורך המשנה — חתימת התורה שבעל פה הראשונה.",
    books: [{ y: 200, he: "משנה", en: "Mishnah" }],
  },
  {
    era: "tannaim", he: "רבי חייא", en: "Rabbi Chiya",
    born: 150, died: 230, circa: true, region: "eretzIsrael", place: "בבל → טבריה, ארץ ישראל",
    w: "רבי חייא", note: "תלמיד-חבר של רבי; מאחרוני התנאים, ליקט ברייתות (תוספתא).",
    books: [],
  },
  {
    era: "tannaim", he: "בר קפרא", en: "Bar Kappara",
    born: 150, died: 220, circa: true, region: "eretzIsrael", place: "לוד, ארץ ישראל",
    w: "בר קפרא", note: "מתלמידי רבי; ליקט משנת ברייתות וידוע במשליו וחידותיו.",
    books: [],
  },
  {
    era: "tannaim", he: "רבי אושעיא", en: "Rabbi Oshaya",
    born: 160, died: 240, circa: true, region: "eretzIsrael", place: "קיסריה, ארץ ישראל",
    w: "רבי אושעיא", note: "'אבי המשנה'; ליקט ברייתות מוסמכות ועמד בראש ישיבת קיסריה.",
    books: [],
  },

  // ---------- AMORAIM (Talmud era) ----------
  {
    era: "amoraim", he: "רב (אבא אריכא)", en: "Rav (Abba Arika)",
    born: 175, died: 247, circa: true, region: "bavel", place: "סורא, בבל",
    w: "רב (אמורא)", note: "ייסד את ישיבת סורא; מראשוני האמוראים בבבל.",
    books: [],
  },
  {
    era: "amoraim", he: "שמואל", en: "Shmuel",
    born: 165, died: 254, circa: true, region: "bavel", place: "נהרדעא, בבל",
    w: "שמואל (אמורא)", note: "ראש ישיבת נהרדעא; 'דינא דמלכותא דינא'.",
    books: [],
  },
  {
    era: "amoraim", he: "רבי יוחנן", en: "Rabbi Yochanan",
    born: 180, died: 279, circa: true, region: "eretzIsrael", place: "טבריה, ארץ ישראל",
    w: "רבי יוחנן", note: "מנהיג חכמי ארץ ישראל; יסוד התלמוד הירושלמי.",
    books: [],
  },
  {
    era: "amoraim", he: "ריש לקיש", en: "Reish Lakish",
    born: 200, died: 275, circa: true, region: "eretzIsrael", place: "טבריה, ארץ ישראל",
    w: "ריש לקיש", note: "בר הפלוגתא והגיס של ר' יוחנן.",
    books: [],
  },
  {
    era: "amoraim", he: "רבי יהושע בן לוי", en: "Rabbi Yehoshua ben Levi",
    born: 170, died: 250, circa: true, region: "eretzIsrael", place: "לוד, ארץ ישראל",
    w: "רבי יהושע בן לוי", note: "מראשוני אמוראי ארץ ישראל; גדול בהלכה ובאגדה.",
    books: [],
  },
  {
    era: "amoraim", he: "רב הונא", en: "Rav Huna",
    born: 216, died: 296, circa: true, region: "bavel", place: "סורא, בבל",
    w: "רב הונא", note: "ראש ישיבת סורא לאחר רב; הנהיג את יהדות בבל.",
    books: [],
  },
  {
    era: "amoraim", he: "רב ששת", en: "Rav Sheshet",
    born: 230, died: 309, circa: true, region: "bavel", place: "נהרדעא → מחוזא, בבל",
    w: "רב ששת", note: "אמורא בבלי שהיה סגי-נהור; בקי בכל המשניות והברייתות בעל פה.",
    books: [],
  },
  {
    era: "amoraim", he: "רב אסי", en: "Rav Assi",
    born: 200, died: 290, circa: true, region: "bavel", place: "הוצל, בבל",
    w: "רב אסי", note: "אמורא בבלי; חברו של רב הונא בהנהגת יהדות בבל.",
    books: [],
  },
  {
    era: "amoraim", he: "רב חסדא", en: "Rav Chisda",
    born: 217, died: 309, circa: true, region: "bavel", place: "סורא, בבל",
    w: "רב חסדא", note: "תלמיד רב; ראש ישיבת סורא ומבכירי אמוראי בבל.",
    books: [],
  },
  {
    era: "amoraim", he: "רבה בר אבוה", en: "Rabbah bar Avuha",
    born: 200, died: 270, circa: true, region: "bavel", place: "נהרדעא, בבל",
    w: "רבה בר אבוה", note: "אמורא בבלי ממשפחת ריש גלותא; רבו וחותנו של רב נחמן.",
    books: [],
  },
  {
    era: "amoraim", he: "רב נחמן (בר יעקב)", en: "Rav Nachman (bar Yaakov)",
    born: 235, died: 320, circa: true, region: "bavel", place: "נהרדעא, בבל",
    w: "רב נחמן", note: "דיין מובהק בנהרדעא; \"הלכה כרב נחמן בדיני\".",
    books: [],
  },
  {
    era: "amoraim", he: "עולא", en: "Ulla",
    born: 250, died: 310, circa: true, region: "eretzIsrael", place: "ארץ ישראל → בבל",
    w: "עולא", note: "אמורא 'נחותא'; נשא הלכות מארץ ישראל לבבל ולהפך.",
    books: [],
  },
  {
    era: "amoraim", he: "רבה (בר נחמני)", en: "Rabbah bar Nachmani",
    born: 270, died: 330, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "רבה בר נחמני", note: "ראש ישיבת פומבדיתא; 'עוקר הרים'.",
    books: [],
  },
  {
    era: "amoraim", he: "אביי", en: "Abaye",
    born: 280, died: 337, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "אביי", note: "ראש ישיבת פומבדיתא; 'הוויות דאביי ורבא'.",
    books: [],
  },
  {
    era: "amoraim", he: "רבא", en: "Rava",
    born: 280, died: 352, circa: true, region: "bavel", place: "מחוזא, בבל",
    w: "רבא", note: "ראש הישיבה במחוזא; הלכה כמותו ברוב מחלוקותיו עם אביי.",
    books: [],
  },
  {
    era: "amoraim", he: "רמי בר חמא", en: "Rami bar Hama",
    born: 270, died: 325, circa: true, region: "bavel", place: "בבל",
    w: "רמי בר חמא", note: "אמורא חריף; חתנו של רב חסדא ובר-הפלוגתא של רבא.",
    books: [],
  },
  {
    era: "amoraim", he: "רב פפא", en: "Rav Pappa",
    born: 300, died: 375, circa: true, region: "bavel", place: "נרש, בבל",
    w: "רב פפא", note: "תלמיד אביי ורבא; ייסד את הישיבה בנרש.",
    books: [],
  },
  {
    era: "amoraim", he: "רב נחמן בר יצחק", en: "Rav Nachman bar Yitzchak",
    born: 280, died: 356, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "רב נחמן בר יצחק", note: "תלמיד רבא; ראש ישיבת פומבדיתא לאחריו.",
    books: [],
  },
  {
    era: "amoraim", he: "רב אשי", en: "Rav Ashi",
    born: 352, died: 427, circa: true, region: "bavel", place: "מתא מחסיא (סורא), בבל",
    w: "רב אשי", note: "החל בעריכת התלמוד הבבלי בישיבת סורא.",
    books: [],
  },
  {
    era: "amoraim", he: "מר זוטרא", en: "Mar Zutra",
    born: 350, died: 417, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "מר זוטרא", note: "מראשי הישיבות בדור שלפני חתימת התלמוד.",
    books: [],
  },
  {
    era: "amoraim", he: "מר בר רב אשי", en: "Mar bar Rav Ashi",
    born: 400, died: 468, circa: true, region: "bavel", place: "מתא מחסיא (סורא), בבל",
    w: "מר בר רב אשי", note: "בנו של רב אשי; ראש ישיבת סורא בדור האחרון לאמוראים.",
    books: [],
  },
  {
    era: "amoraim", he: "רבינא", en: "Ravina",
    born: 420, died: 499, circa: true, region: "bavel", place: "סורא, בבל",
    w: "רבינא", note: "מחותמי התלמוד הבבלי — 'רב אשי ורבינא סוף הוראה'.",
    books: [],
  },
  {
    era: "amoraim", he: "רבי תנחומא", en: "Rabbi Tanchuma",
    born: 350, died: 420, circa: true, region: "eretzIsrael", place: "ארץ ישראל",
    w: "רבי תנחומא", note: "מבעלי האגדה בארץ ישראל; מדרש תנחומא מיוחס לו.",
    books: [],
  },

  // ---------- GEONIM ----------
  {
    era: "geonim", he: "רב חנן מאישקיא", en: "Rav Chanan of Iskiya",
    born: 589, died: 609, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "חנן מאישקיא", note: "ראשון גאוני פומבדיתא — ראשית תקופת הגאונים (כ-589).",
    books: [],
  },
  {
    era: "geonim", he: "רב אחאי גאון (בעל השאילתות)", en: "Rav Achai Gaon (She'iltot)",
    born: 680, died: 752, circa: true, region: "bavel", place: "שבחא, בבל → ארץ ישראל",
    w: "רב אחא משבחא", note: "מחבר ה'שאילתות' — הספר המחברי הראשון לאחר חתימת התלמוד.",
    books: [{ y: 750, he: "שאילתות דרב אחאי", en: "She'iltot (first authored post-Talmudic work)" }],
  },
  {
    era: "geonim", he: "רב יהודאי גאון", en: "Rav Yehudai Gaon",
    born: 700, died: 761, circa: true, region: "bavel", place: "סורא, בבל",
    w: "יהודאי גאון", note: "מראשוני הגאונים שכתבו ספרי פסיקה.",
    books: [{ y: 755, he: "הלכות פסוקות", en: "Halachot Pesukot" }],
  },
  {
    era: "geonim", he: "רב עמרם גאון", en: "Rav Amram Gaon",
    born: 810, died: 875, circa: true, region: "bavel", place: "סורא, בבל",
    w: "עמרם גאון", note: "ראש ישיבת סורא; ערך את סדר התפילה הראשון השלם.",
    books: [{ y: 860, he: "סדר רב עמרם גאון", en: "Seder Rav Amram (first ordered siddur)" }],
  },
  {
    era: "geonim", he: "רב יהודה בן שמואל גאון", en: "Rav Yehuda ben Shmuel Gaon",
    born: 855, died: 917, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "יהודה בן שמואל גאון", note: "גאון פומבדיתא (תרס\"ה–תרע\"ז); אבי שושלת הגאונים — סבו של רב שרירא וזקנו של רב האי גאון.",
    books: [],
  },
  {
    era: "geonim", he: "רב סעדיה גאון (רס\"ג)", en: "Rav Saadia Gaon",
    born: 882, died: 942, region: "bavel", place: "פיום, מצרים → סורא",
    w: "רב סעדיה גאון", note: "פילוסוף, מדקדק ופרשן; נלחם בקראים.",
    books: [
      { y: 933, he: "אמונות ודעות", en: "Emunot ve-De'ot (philosophy)" },
      { y: 920, he: "תפסיר (תרגום התורה)", en: "Tafsir — Arabic Torah translation" },
    ],
  },
  {
    era: "geonim", he: "רב נחמיה בן כהן צדק גאון", en: "Nehemiah ben Kohen Tzedek (Gaon)",
    born: 900, died: 968, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "נחמיה בן כהן צדק", note: "ראש ישיבת פומבדיתא בדור שלפני רב שרירא גאון.",
    books: [],
  },
  {
    era: "geonim", he: "רב שרירא גאון", en: "Rav Sherira Gaon",
    born: 906, died: 1006, circa: true, region: "bavel", place: "פומבדיתא, בבל",
    w: "רב שרירא גאון", note: "כתב את ההיסטוריה של מסירת התורה שבעל פה.",
    books: [{ y: 987, he: "איגרת רב שרירא גאון", en: "Iggeret Rav Sherira (history of the Oral Law)" }],
  },
  {
    era: "geonim", he: "רב האי גאון", en: "Rav Hai Gaon",
    born: 939, died: 1038, region: "bavel", place: "פומבדיתא, בבל",
    w: "רב האי גאון", note: "אחרון גאוני בבל הגדולים; אלפי תשובות.",
    books: [{ y: 1000, he: "ספר המקח והממכר", en: "Sefer ha-Mekach (commercial law)" }],
  },

  // ---------- RISHONIM ----------
  {
    era: "rishonim", he: "רבנו גרשום מאור הגולה", en: "Rabbeinu Gershom",
    born: 960, died: 1028, circa: true, region: "ashkenaz", place: "מגנצא, אשכנז",
    w: "רבנו גרשום", note: "\"מאור הגולה\"; תקנות (חרם נגד פוליגמיה).",
    books: [{ y: 1000, he: "תקנות רבנו גרשום", en: "Takkanot (rabbinic ordinances)" }],
  },
  {
    era: "rishonim", he: "רבנו חננאל", en: "Rabbeinu Chananel",
    born: 990, died: 1053, circa: true, region: "tzfonAfrica", place: "קירואן, צפון אפריקה",
    w: "רבנו חננאל", note: "מראשוני מפרשי התלמוד; חוליה מקשרת בין הגאונים לראשונים.",
    books: [{ y: 1040, he: "פירוש רבנו חננאל על הש\"ס", en: "Continuous Talmud commentary" }],
  },
  {
    era: "rishonim", he: "ר' שמואל הנגיד", en: "Shmuel HaNagid",
    born: 993, died: 1056, region: "sefarad", place: "גרנדה, ספרד",
    w: "שמואל הנגיד", note: "נגיד יהדות ספרד; מצביא, מדינאי, משורר ותלמודיסט בתור הזהב.",
    books: [{ y: 1050, he: "הלכתא גברוותא / בן משלי", en: "Hilkheta Gavrata; poetry" }],
  },
  {
    era: "rishonim", he: "ר' שלמה אבן גבירול", en: "Shlomo ibn Gabirol",
    born: 1021, died: 1058, circa: true, region: "sefarad", place: "מאלגה, ספרד",
    w: "שלמה אבן גבירול", note: "משורר ופילוסוף ניאו-אפלטוני.",
    books: [{ y: 1045, he: "כתר מלכות / מקור חיים", en: "Keter Malchut; Fons Vitae" }],
  },
  {
    era: "rishonim", he: "רי\"ף (יצחק אלפסי)", en: "Rif (Isaac Alfasi)",
    born: 1013, died: 1103, region: "sefarad", place: "פאס → לוסנה, ספרד",
    w: "יצחק אלפסי", note: "ספר ההלכות — אבן יסוד של ספרות הפסיקה.",
    books: [{ y: 1080, he: "ספר ההלכות (הרי\"ף)", en: "Sefer ha-Halachot" }],
  },
  {
    era: "rishonim", he: "ר\"י מיגאש", en: "Ri Migash (Joseph ibn Migash)",
    born: 1077, died: 1141, region: "sefarad", place: "לוסנה, ספרד",
    w: "ר\"י מיגאש", note: "יורש הרי\"ף בראשות ישיבת לוסנה; רבו של אבי הרמב\"ם וחוליה אל הרמב\"ם.",
    books: [{ y: 1130, he: "חידושי הר\"י מיגאש", en: "Talmudic novellae & responsa" }],
  },
  {
    era: "rishonim", he: "ר' יעקב בן יקר", en: "Yaakov ben Yakar",
    born: 990, died: 1064, circa: true, region: "ashkenaz", place: "מגנצא → וורמייזא, אשכנז",
    w: "יעקב בן יקר", note: "מתלמידי רבנו גרשום וראש ישיבת וורמס; רבו המובהק של רש\"י.",
    books: [],
  },
  {
    era: "rishonim", he: "רש\"י", en: "Rashi (Shlomo Yitzchaki)",
    born: 1040, died: 1105, region: "tzarfat", place: "טרואה, צרפת",
    w: "רש\"י", note: "הפרשן הגדול ביותר על התנ\"ך והתלמוד.",
    books: [
      { y: 1090, he: "פירוש רש\"י על התורה", en: "Commentary on the Torah" },
      { y: 1100, he: "פירוש רש\"י על הש\"ס", en: "Commentary on the Talmud" },
    ],
  },
  {
    era: "rishonim", he: "בעל הערוך (ר' נתן מרומי)", en: "Arukh (Nathan ben Yechiel of Rome)",
    born: 1035, died: 1103, circa: true, region: "italia", place: "רומא, איטליה",
    w: "נתן מרומי", note: "ראש ישיבת רומא; חיבר את \"הערוך\" — המילון הקלאסי לתלמוד ולמדרשים.",
    books: [{ y: 1101, he: "ספר הערוך", en: "Sefer he-Arukh (Talmudic lexicon)" }],
  },
  {
    era: "rishonim", he: "ר' קלונימוס הזקן", en: "Kalonymus ben Yitzchak (the Elder)",
    born: 1030, died: 1126, circa: true, region: "ashkenaz", place: "מגנצא → שפיירא, אשכנז",
    w: "קלונימוס הזקן", note: "ממשפחת קלונימוס שהעבירה את התורה מאיטליה לאשכנז; מנהיג ומקובל בדור גזרות תתנ\"ו (מסע הצלב הראשון).",
    books: [],
  },
  {
    era: "rishonim", he: "ר' בחיי אבן פקודה", en: "Bahya ibn Paquda",
    born: 1050, died: 1120, circa: true, region: "sefarad", place: "סרגוסה, ספרד",
    w: "בחיי אבן פקודה", note: "מספרי המוסר והמחשבה הקלאסיים.",
    books: [{ y: 1080, he: "חובות הלבבות", en: "Chovot ha-Levavot (Duties of the Heart)" }],
  },
  {
    era: "rishonim", he: "ר' יהודה הלוי", en: "Yehuda HaLevi",
    born: 1075, died: 1141, circa: true, region: "sefarad", place: "טודלה, ספרד → ארץ ישראל",
    w: "יהודה הלוי", note: "משורר ופילוסוף; משורר \"ציון הלא תשאלי\".",
    books: [{ y: 1140, he: "ספר הכוזרי", en: "The Kuzari" }],
  },
  {
    era: "rishonim", he: "רשב\"ם", en: "Rashbam (Shmuel ben Meir)",
    born: 1085, died: 1158, circa: true, region: "tzarfat", place: "טרואה, צרפת",
    w: "רשב\"ם", note: "נכד רש\"י; פרשן הפשט ובעל תוספות.",
    books: [{ y: 1140, he: "פירוש רשב\"ם על התורה", en: "Commentary on the Torah (peshat)" }],
  },
  {
    era: "rishonim", he: "אבן עזרא", en: "Abraham ibn Ezra",
    born: 1089, died: 1167, region: "sefarad", place: "טודלה, ספרד (נדודים)",
    w: "אברהם אבן עזרא", note: "פרשן, מדקדק, אסטרונום ומשורר.",
    books: [{ y: 1150, he: "פירוש אבן עזרא על התורה", en: "Torah commentary" }],
  },
  {
    era: "rishonim", he: "רבנו תם", en: "Rabbeinu Tam (Yaakov ben Meir)",
    born: 1100, died: 1171, region: "tzarfat", place: "רמרופ, צרפת",
    w: "רבנו תם", note: "נכד רש\"י; מגדולי בעלי התוספות.",
    books: [{ y: 1150, he: "ספר הישר", en: "Sefer ha-Yashar" }],
  },
  {
    era: "rishonim", he: "ר\"י הזקן (מבעלי התוספות)", en: "Ri HaZaken (Isaac of Dampierre)",
    born: 1115, died: 1184, circa: true, region: "tzarfat", place: "דמפייר, צרפת",
    w: "ר\"י הזקן", note: "מגדולי בעלי התוספות; תלמיד רבנו תם.",
    books: [{ y: 1175, he: "תוספות", en: "Tosafot (Talmudic glosses)" }],
  },
  {
    era: "rishonim", he: "בעל העיטור (יצחק בן אבא מרי)", en: "Baal HaIttur (Isaac ben Abba Mari)",
    born: 1122, died: 1193, circa: true, region: "provans", place: "מרסיי, פרובנס",
    w: "יצחק בן אבא מרי", note: "מחכמי פרובנס; ספרו ההלכתי \"העיטור\" מקור יסוד בדיני שטרות, מועדים ושחיטה.",
    books: [{ y: 1180, he: "ספר העיטור", en: "Sefer ha-Ittur (halachic work)" }],
  },
  {
    era: "rishonim", he: "הראב\"ד השני (בעל האשכול)", en: "Raavad II (Abraham ben Isaac of Narbonne)",
    born: 1110, died: 1179, circa: true, region: "provans", place: "נרבונה, פרובנס",
    w: "אברהם בן יצחק מנרבונה", note: "אב בית דין נרבונה ומגדולי חכמי פרובנס; ספרו \"האשכול\" מספרי ההלכה הקדומים. חותנו ורבו של הראב\"ד מפושקירה.",
    books: [{ y: 1160, he: "ספר האשכול", en: "Sefer ha-Eshkol (halacha)" }],
  },
  {
    era: "rishonim", he: "ראב\"ד (אברהם בן דוד)", en: "Raavad (Abraham ben David of Posquières)",
    born: 1125, died: 1198, region: "provans", place: "פושקירה, פרובנס",
    w: "אברהם בן דוד מפושקירה", note: "מגדולי חכמי פרובנס; השגותיו נדפסות לצד משנה תורה לרמב\"ם.",
    books: [{ y: 1185, he: "השגות הראב\"ד / בעלי הנפש", en: "Hasagot on Mishneh Torah; Ba'alei ha-Nefesh" }],
  },
  {
    era: "rishonim", he: "רמב\"ם (משה בן מימון)", en: "Rambam (Maimonides)",
    born: 1138, died: 1204, region: "sefarad", place: "קורדובה, ספרד → פוסטאט, מצרים",
    w: "רמב\"ם", note: "פוסק, פילוסוף ורופא; \"מִמֹּשֶׁה עד מֹשֶׁה...\".",
    books: [
      { y: 1168, he: "פירוש המשניות", en: "Commentary on the Mishnah" },
      { y: 1180, he: "משנה תורה (י\"ד החזקה)", en: "Mishneh Torah (legal code)" },
      { y: 1190, he: "מורה נבוכים", en: "Guide for the Perplexed" },
    ],
  },
  {
    era: "rishonim", he: "רד\"ק (דוד קמחי)", en: "Radak (David Kimchi)",
    born: 1160, died: 1235, region: "provans", place: "נרבונה, פרובנס",
    w: "דוד קמחי", note: "מדקדק ופרשן הנ\"ך.",
    books: [{ y: 1210, he: "ספר השורשים / פירוש הנ\"ך", en: "Sefer ha-Shorashim; Bible commentary" }],
  },
  {
    era: "rishonim", he: "ראבי\"ה (אליעזר בן יואל הלוי)", en: "Raavyah (Eliezer ben Joel HaLevi)",
    born: 1140, died: 1225, circa: true, region: "ashkenaz", place: "קלן, אשכנז",
    w: "אליעזר בן יואל", note: "מגדולי חכמי אשכנז ונכד הראב\"ן; רבו של בעל אור זרוע. ספרו \"אבי העזרי\" (ראבי\"ה) מאוצרות הפסיקה האשכנזית.",
    books: [{ y: 1200, he: "ספר ראבי\"ה (אבי העזרי)", en: "Sefer Raavyah (Avi ha-Ezri)" }],
  },
  {
    era: "rishonim", he: "רבי יהודה החסיד", en: "Yehuda HeChasid (of Regensburg)",
    born: 1150, died: 1217, circa: true, region: "ashkenaz", place: "שפיירא → רגנסבורג, אשכנז",
    w: "יהודה החסיד", note: "מנהיג חסידי אשכנז; חיבר את \"ספר חסידים\" — מיסודות תורת המוסר והאדיקות האשכנזית.",
    books: [{ y: 1200, he: "ספר חסידים", en: "Sefer Chasidim" }],
  },
  {
    era: "rishonim", he: "הרוקח (ר' אלעזר מוורמייזא)", en: "Rokeach (Elazar of Worms)",
    born: 1176, died: 1238, circa: true, region: "ashkenaz", place: "וורמייזא, אשכנז",
    w: "אלעזר מגרמייזא", note: "מאחרוני חסידי אשכנז ותלמיד ר' יהודה החסיד; פוסק ומקובל, בעל \"ספר הרוקח\".",
    books: [{ y: 1220, he: "ספר הרוקח", en: "Sefer ha-Rokeach (halacha)" }],
  },
  {
    era: "rishonim", he: "ר' שמשון מקוצי", en: "Samson of Coucy",
    born: 1150, died: 1220, circa: true, region: "tzarfat", place: "קוצי, צרפת",
    w: "שמשון מקוצי", note: "מבעלי התוספות; תלמיד ר\"י הזקן, גיסו של בעל הסמ\"ג ורבו של בעל אור זרוע.",
    books: [{ y: 1200, he: "תוספות", en: "Tosafot (Talmudic glosses)" }],
  },
  {
    era: "rishonim", he: "אור זרוע (ר' יצחק מווינה)", en: "Or Zarua (Isaac of Vienna)",
    born: 1180, died: 1250, circa: true, region: "ashkenaz", place: "אשכנז → וינה",
    w: "יצחק מווינה", note: "מבעלי התוספות; תלמיד הראבי\"ה ורבו של המהר\"ם. ספרו \"אור זרוע\" אוצר מנהגי אשכנז וצרפת.",
    books: [{ y: 1240, he: "ספר אור זרוע", en: "Sefer Or Zarua (halacha & customs)" }],
  },
  {
    era: "rishonim", he: "רמב\"ן (משה בן נחמן)", en: "Ramban (Nachmanides)",
    born: 1194, died: 1270, region: "sefarad", place: "גירונה, ספרד → ארץ ישראל",
    w: "רמב\"ן", note: "פרשן, מקובל ופוסק; ויכוח ברצלונה.",
    books: [{ y: 1267, he: "פירוש הרמב\"ן על התורה", en: "Commentary on the Torah" }],
  },
  {
    era: "rishonim", he: "רבנו יונה גירונדי", en: "Rabbeinu Yonah of Gerona",
    born: 1200, died: 1263, circa: true, region: "sefarad", place: "גירונה, ספרד",
    w: "יונה גירונדי", note: "ספרי מוסר קלאסיים.",
    books: [{ y: 1260, he: "שערי תשובה", en: "Sha'arei Teshuvah (gates of repentance)" }],
  },
  {
    era: "rishonim", he: "רבנו יחיאל מפריז", en: "Yechiel of Paris",
    born: 1200, died: 1265, circa: true, region: "tzarfat", place: "פריז → עכו",
    w: "יחיאל מפריז", note: "ראש ישיבת פריז ומבעלי התוספות; עמד בראש הצד היהודי בוויכוח פריז (1240). בערוב ימיו עלה לארץ ישראל.",
    books: [{ y: 1240, he: "תוספות / פסקים", en: "Tosafot; halachic rulings" }],
  },
  {
    era: "rishonim", he: "סמ\"ג (ר' משה מקוצי)", en: "Semag (Moses of Coucy)",
    born: 1200, died: 1260, circa: true, region: "tzarfat", place: "קוצי, צרפת",
    w: "משה מקוצי", note: "מבעלי התוספות; דרשן שעורר לתשובה בקהילות ספרד, וחיבר את \"ספר מצוות גדול\" (סמ\"ג) — מניין מקיף של תרי\"ג המצוות.",
    books: [{ y: 1247, he: "ספר מצוות גדול (סמ\"ג)", en: "Sefer Mitzvot Gadol (Semag)" }],
  },
  {
    era: "rishonim", he: "סמ\"ק (ר' יצחק מקורביל)", en: "Semak (Isaac of Corbeil)",
    born: 1210, died: 1280, circa: true, region: "tzarfat", place: "קורביל, צרפת",
    w: "יצחק מקורביל", note: "מבעלי התוספות וחתנו של רבנו יחיאל מפריז; חיבר את \"ספר מצוות קטן\" (סמ\"ק / עמודי גולה) שנפוץ מאוד בקהילות.",
    books: [{ y: 1277, he: "ספר מצוות קטן (סמ\"ק)", en: "Sefer Mitzvot Katan (Semak)" }],
  },
  {
    era: "rishonim", he: "רבנו פרץ (מקורביל)", en: "Peretz ben Elijah",
    born: 1230, died: 1295, circa: true, region: "tzarfat", place: "קורביל, צרפת",
    w: "רבנו פרץ", note: "מאחרוני בעלי התוספות בצרפת; הגהותיו על הסמ\"ק נדפסות לצדו, וכן חיבר תוספות ופסקים.",
    books: [{ y: 1290, he: "הגהות רבנו פרץ / תוספות", en: "Glosses on the Semak; Tosafot" }],
  },
  {
    era: "rishonim", he: "מהר\"ם מרוטנבורג (מאיר ב\"ר ברוך)", en: "Maharam of Rothenburg",
    born: 1220, died: 1293, circa: true, region: "ashkenaz", place: "וורמס → רוטנבורג, אשכנז",
    w: "מהר\"ם מרוטנבורג", note: "מנהיג יהדות אשכנז ומאחרוני בעלי התוספות; רבו של הרא\"ש. נכלא במבצר אנזיסהיים וסירב להיפדות.",
    books: [{ y: 1280, he: "שו\"ת מהר\"ם מרוטנבורג / תוספות", en: "Responsa; Tosafot" }],
  },
  {
    era: "rishonim", he: "רשב\"א", en: "Rashba (Shlomo ibn Aderet)",
    born: 1235, died: 1310, region: "sefarad", place: "ברצלונה, ספרד",
    w: "שלמה בן אדרת", note: "\"הרב מברצלונה\"; אלפי תשובות.",
    books: [{ y: 1300, he: "שו\"ת הרשב\"א", en: "Responsa of the Rashba" }],
  },
  {
    era: "rishonim", he: "ריטב\"א (יום טוב אשבילי)", en: "Ritva (Yom Tov of Seville)",
    born: 1260, died: 1320, circa: true, region: "sefarad", place: "סרגוסה, ספרד",
    w: "ריטב\"א", note: "מתלמידי הרשב\"א והרא\"ה; חידושיו הבהירים על הש\"ס מהיסודיים שבלימוד.",
    books: [{ y: 1310, he: "חידושי הריטב\"א", en: "Chiddushei ha-Ritva (Talmud novellae)" }],
  },
  {
    era: "rishonim", he: "המאירי", en: "Meiri (Menachem ben Shlomo)",
    born: 1249, died: 1315, region: "provans", place: "פרפיניאן, פרובנס",
    w: "מנחם המאירי", note: "פירוש מקיף ובהיר על התלמוד.",
    books: [{ y: 1300, he: "בית הבחירה", en: "Beit ha-Bechirah (Talmud commentary)" }],
  },
  {
    era: "rishonim", he: "רא\"ש (אשר בן יחיאל)", en: "Rosh (Asher ben Yechiel)",
    born: 1250, died: 1327, region: "sefarad", place: "אשכנז → טולדו, ספרד",
    w: "אשר בן יחיאל", note: "גשר בין מסורת אשכנז לספרד.",
    books: [{ y: 1320, he: "פסקי הרא\"ש", en: "Piskei ha-Rosh (halachic digest)" }],
  },
  {
    era: "rishonim", he: "המרדכי (מרדכי בן הלל)", en: "Mordechai (Mordechai ben Hillel)",
    born: 1250, died: 1298, circa: true, region: "ashkenaz", place: "נירנברג, אשכנז",
    w: "מרדכי בן הלל", note: "תלמיד המהר\"ם; ספר \"המרדכי\" — לקט פסקי אשכנז וצרפת, נדפס לצד הרי\"ף. נספה בגזרות רינטפליש.",
    books: [{ y: 1290, he: "ספר המרדכי", en: "Sefer ha-Mordechai (halachic compendium)" }],
  },
  {
    era: "rishonim", he: "הגהות מיימוניות (מאיר הכהן)", en: "Hagahot Maimoniyot (Meir HaKohen)",
    born: 1260, died: 1298, circa: true, region: "ashkenaz", place: "רוטנבורג, אשכנז",
    w: "מאיר הכהן מרוטנבורג", note: "מתלמידי המהר\"ם; הגהותיו על משנה תורה לרמב\"ם נדפסות כאחד מנושאי כליו. נספה בגזרות רינטפליש.",
    books: [{ y: 1295, he: "הגהות מיימוניות", en: "Hagahot Maimoniyot (on Mishneh Torah)" }],
  },
  {
    era: "rishonim", he: "תשב\"ץ קטן (שמשון בן צדוק)", en: "Tashbetz Katan (Samson ben Zadok)",
    born: 1250, died: 1312, circa: true, region: "ashkenaz", place: "אשכנז",
    w: "שמשון בן צדוק", note: "מתלמידי המהר\"ם; ליווהו במאסר ותיעד את מנהגיו ופסקיו ב\"תשב\"ץ קטן\". שותף לחיבור הגהות מיימוניות.",
    books: [{ y: 1300, he: "תשב\"ץ קטן", en: "Tashbetz Katan (Maharam's customs & rulings)" }],
  },
  {
    era: "rishonim", he: "רלב\"ג (גרשון)", en: "Ralbag (Gersonides)",
    born: 1288, died: 1344, region: "provans", place: "באניולס, פרובנס",
    w: "רלב\"ג", note: "פרשן, פילוסוף, מתמטיקאי ואסטרונום.",
    books: [{ y: 1329, he: "מלחמות השם / פירוש הנ\"ך", en: "Milchamot Hashem; Bible commentary" }],
  },
  {
    era: "rishonim", he: "בעל הטורים (יעקב בן אשר)", en: "Tur (Yaakov ben Asher)",
    born: 1269, died: 1343, region: "sefarad", place: "טולדו, ספרד",
    w: "יעקב בן אשר", note: "בנו של הרא\"ש; חילק את ההלכה לארבעה טורים.",
    books: [{ y: 1330, he: "ארבעה טורים", en: "Arba'ah Turim (four-part code)" }],
  },
  {
    era: "rishonim", he: "רבינו ירוחם (בן משולם)", en: "Rabbeinu Yerucham (ben Meshullam)",
    born: 1290, died: 1350, circa: true, region: "sefarad", place: "פרובנס → טולדו, ספרד",
    w: "ירוחם בן משולם", note: "מתלמידי הרא\"ש בטולדו; פוסק מרכזי, רבים מדבריו הובאו בבית יוסף.",
    books: [
      { y: 1334, he: "ספר מישרים", en: "Sefer Meisharim (civil law)" },
      { y: 1340, he: "תולדות אדם וחוה", en: "Toldot Adam ve-Chavah (practical halacha)" },
    ],
  },
  {
    era: "rishonim", he: "כפתור ופרח (אשתורי הפרחי)", en: "Ishtori Haparchi",
    born: 1280, died: 1355, circa: true, region: "eretzIsrael", place: "פרובנס → בית שאן",
    w: "אשתורי הפרחי", note: "מגורשי צרפת שעלה לארץ ישראל; חיבר את \"כפתור ופרח\" — הספר הראשון בגאוגרפיה של ארץ ישראל ובמצוות התלויות בארץ.",
    books: [{ y: 1322, he: "כפתור ופרח", en: "Kaftor va-Ferach (geography & laws of the Land)" }],
  },
  // -- late Rishonim (the 14th–15th-c. that previously left a gap) --
  {
    era: "rishonim", he: "ר\"ן (נסים גירונדי)", en: "Ran (Nissim of Gerona)",
    born: 1320, died: 1376, region: "sefarad", place: "ברצלונה, ספרד",
    w: "ר\"ן", note: "מגדולי פרשני התלמוד וההלכה בספרד.",
    books: [{ y: 1365, he: "חידושי הר\"ן / דרשות הר\"ן", en: "Commentaries; Derashot ha-Ran" }],
  },
  {
    era: "rishonim", he: "ריב\"ש (יצחק בר ששת)", en: "Rivash (Isaac ben Sheshet)",
    born: 1326, died: 1408, region: "sefarad", place: "ברצלונה → אלג'יר",
    w: "יצחק בר ששת", note: "מגדולי הפוסקים; שו\"ת רב-השפעה.",
    books: [{ y: 1400, he: "שו\"ת הריב\"ש", en: "Responsa of the Rivash" }],
  },
  {
    era: "rishonim", he: "רשב\"ץ (שמעון בן צמח)", en: "Rashbatz (Shimon b. Tzemach Duran)",
    born: 1361, died: 1444, region: "tzfonAfrica", place: "מיורקה → אלג'יר",
    w: "שמעון בן צמח דוראן", note: "פוסק, רופא ופילוסוף ביהדות צפון אפריקה.",
    books: [{ y: 1420, he: "שו\"ת התשב\"ץ / מגן אבות", en: "Tashbetz responsa; Magen Avot" }],
  },
  {
    era: "rishonim", he: "ר' יוסף אלבו (העיקרים)", en: "Rabbi Yosef Albo (Sefer HaIkkarim)",
    born: 1380, died: 1444, circa: true, region: "sefarad", place: "סרגוסה, ספרד",
    w: "יוסף אלבו", note: "פילוסוף יהודי ותלמיד רבי חסדאי קרשקש; זיקק את עיקרי האמונה.",
    books: [{ y: 1425, he: "ספר העיקרים", en: "Sefer HaIkkarim" }],
  },
  {
    era: "rishonim", he: "מהרי\"ל (יעקב מולין)", en: "Maharil (Yaakov Moelin)",
    born: 1365, died: 1427, region: "ashkenaz", place: "מגנצא, אשכנז",
    w: "יעקב מולין", note: "אבי מנהגי אשכנז; בסיס לפסיקת הרמ\"א.",
    books: [{ y: 1420, he: "ספר מהרי\"ל (מנהגים)", en: "Sefer Maharil (Ashkenazi customs)" }],
  },
  {
    era: "rishonim", he: "ר' ישראל איסרלן (תרומת הדשן)", en: "Israel Isserlein (Terumat HaDeshen)",
    born: 1390, died: 1460, region: "ashkenaz", place: "וינר נוישטאדט, אוסטריה",
    w: "ישראל איסרלן", note: "מגדולי פוסקי אשכנז במאה ה-15; שו\"ת רב-השפעה על פסיקת הרמ\"א.",
    books: [{ y: 1519, he: "תרומת הדשן (שו\"ת)", en: "Terumat HaDeshen (responsa)" }],
  },
  {
    era: "rishonim", he: "מהרי\"ק (יוסף קולון)", en: "Maharik (Joseph Colon)",
    born: 1420, died: 1480, circa: true, region: "italia", place: "איטליה",
    w: "יוסף קולון", note: "גדול פוסקי איטליה במאה ה-15.",
    books: [{ y: 1470, he: "שו\"ת מהרי\"ק", en: "Responsa of the Maharik" }],
  },
  {
    era: "rishonim", he: "ר' יצחק אברבנאל", en: "Don Isaac Abarbanel",
    born: 1437, died: 1508, region: "sefarad", place: "ליסבון → איטליה",
    w: "יצחק אברבנאל", note: "פרשן, פילוסוף ומדינאי; מגורשי ספרד.",
    books: [{ y: 1495, he: "פירוש אברבנאל על התנ\"ך", en: "Bible commentary" }],
  },
  {
    era: "rishonim", he: "ר' עובדיה מברטנורא", en: "Obadiah of Bertinoro",
    born: 1445, died: 1515, circa: true, region: "italia", place: "איטליה → ירושלים",
    w: "עובדיה מברטנורא", note: "פירוש המשניות הנפוץ ביותר.",
    books: [{ y: 1500, he: "פירוש הברטנורא על המשנה", en: "Mishnah commentary" }],
  },
  {
    era: "rishonim", he: "ספר יוחסין (ר' אברהם זכות)", en: "Abraham Zacuto (Sefer Yuchasin)",
    born: 1452, died: 1515, circa: true, region: "sefarad", place: "סלמנקה, ספרד → תוניס",
    w: "אברהם זכות", note: "אסטרונום, היסטוריון ופוסק מגורשי ספרד; חיבר את \"ספר יוחסין\" — כרוניקה של שלשלת מסירת התורה, ולוחות אסטרונומיים ששימשו את המגלים.",
    books: [{ y: 1504, he: "ספר יוחסין", en: "Sefer Yuchasin (chronicle)" }],
  },

  // ---------- ACHARONIM ----------
  {
    era: "acharonim", he: "ר' יעקב פולק", en: "Rabbi Yaakov Pollak",
    born: 1465, died: 1541, circa: true, region: "mizrachEurope", place: "פראג → קרקוב",
    w: "יעקב פולק", note: "מראשוני בוני מרכז התורה בפולין; \"בעל החילוקים\" ומאבות הפלפול.",
    books: [],
  },
  {
    era: "acharonim", he: "מהר\"י בירב", en: "Maharibi (Yaakov Beirav)",
    born: 1474, died: 1546, region: "eretzIsrael", place: "ספרד → פאס → צפת",
    w: "יעקב בירב", note: "מגדולי חכמי צפת; ניסה לחדש את הסמיכה בארץ ישראל.",
    books: [],
  },
  {
    era: "acharonim", he: "בית יוסף (ר' יוסף קארו)", en: "Beit Yosef (Yosef Karo)",
    born: 1488, died: 1575, region: "eretzIsrael", place: "טולדו → צפת",
    w: "יוסף קארו", note: "מחבר השולחן ערוך — ספר הפסיקה המרכזי.",
    books: [
      { y: 1542, he: "בית יוסף (על הטור)", en: "Beit Yosef (commentary on the Tur)" },
      { y: 1565, he: "שולחן ערוך", en: "Shulchan Aruch (code of Jewish law)" },
    ],
  },
  {
    era: "acharonim", he: "מהר\"ל מפראג", en: "Maharal of Prague",
    born: 1520, died: 1609, circa: true, region: "merkazEurope", place: "פראג, בוהמיה",
    w: "מהר\"ל", note: "הוגה דעות; מיוחס לו סיפור הגולם.",
    books: [{ y: 1578, he: "גור אריה / נצח ישראל", en: "Gur Aryeh, Netzach Yisrael" }],
  },
  {
    era: "acharonim", he: "רמ\"א (משה איסרליש)", en: "Rema (Moshe Isserles)",
    born: 1530, died: 1572, circa: true, region: "mizrachEurope", place: "קרקוב, פולין",
    w: "משה איסרליש", note: "\"המפה\" — הוסיף את מנהג אשכנז לשו\"ע.",
    books: [{ y: 1570, he: "המפה / דרכי משה", en: "Ha-Mapah (Ashkenazi glosses on Shulchan Aruch)" }],
  },
  {
    era: "acharonim", he: "בעל הלבוש (מרדכי יפה)", en: "Levush (Mordechai Yoffe)",
    born: 1530, died: 1612, circa: true, region: "merkazEurope", place: "פראג → פוזן",
    w: "מרדכי יפה", note: "מתלמידי הרמ\"א והמהרש\"ל; חיבר קודקס הלכתי — \"הלבושים\".",
    books: [{ y: 1590, he: "לבושים", en: "Levushim (halachic code)" }],
  },
  {
    era: "acharonim", he: "מהרש\"ל (שלמה לוריא)", en: "Maharshal (Shlomo Luria)",
    born: 1510, died: 1573, circa: true, region: "mizrachEurope", place: "לובלין, פולין",
    w: "שלמה לוריא", note: "מגדולי פוסקי פולין; בירר את הסוגיה מן התלמוד עד להלכה.",
    books: [{ y: 1565, he: "ים של שלמה / חכמת שלמה", en: "Yam Shel Shlomo; Chochmat Shlomo" }],
  },
  {
    era: "acharonim", he: "מהרש\"א (שמואל אליעזר איידלס)", en: "Maharsha (Shmuel Eidels)",
    born: 1555, died: 1631, region: "mizrachEurope", place: "אוסטרהא, פולין",
    w: "שמואל אליעזר הלוי איידלס", note: "מגדולי מפרשי התלמוד; חידושיו על ההלכות והאגדות נדפסים בכל ש\"ס.",
    books: [{ y: 1612, he: "חידושי הלכות ואגדות", en: "Chiddushei Halachot va-Aggadot" }],
  },
  {
    era: "acharonim", he: "השל\"ה הקדוש (ישעיה הורוביץ)", en: "Shelah (Isaiah Horowitz)",
    born: 1565, died: 1630, region: "eretzIsrael", place: "פראג → ירושלים",
    w: "ישעיה הלוי הורוביץ", note: "מקובל ופוסק; חיבורו רב-ההשפעה משלב הלכה, מוסר וקבלה.",
    books: [{ y: 1649, he: "שני לוחות הברית (של\"ה)", en: "Shnei Luchot HaBrit" }],
  },
  {
    era: "acharonim", he: "סמ\"ע (יהושע פלק כץ)", en: "Sma (Yehoshua Falk Katz)",
    born: 1555, died: 1614, region: "mizrachEurope", place: "לבוב, פולין",
    w: "יהושע פלק כץ", note: "מפרש מרכזי על חושן משפט; חיבר גם דרישה ופרישה על הטור.",
    books: [{ y: 1614, he: "ספר מאירת עיניים (סמ\"ע)", en: "Sefer Me'irat Einayim (Sma)" }],
  },
  {
    era: "acharonim", he: "תוספות יום טוב (יו\"ט ליפמן הלר)", en: "Tosafot Yom Tov (Yom Tov Lipmann Heller)",
    born: 1579, died: 1654, region: "merkazEurope", place: "פראג → קרקוב",
    w: "יום-טוב ליפמן הלר", note: "מתלמידי המהר\"ל; פירושו על המשנה מן המרכזיים שבדפוסי המשניות.",
    books: [{ y: 1617, he: "תוספות יום טוב (על המשנה)", en: "Tosafot Yom Tov (Mishnah commentary)" }],
  },
  {
    era: "acharonim", he: "מגלה עמוקות (נתן נטע שפירא)", en: "Megaleh Amukot (Nathan Nata Spira)",
    born: 1585, died: 1633, region: "mizrachEurope", place: "קרקוב, פולין",
    w: "נתן נטע שפירא", note: "מקובל ורבה של קרקוב; חיבורו על דרך הסוד והרמז.",
    books: [{ y: 1637, he: "מגלה עמוקות", en: "Megaleh Amukot" }],
  },
  {
    era: "acharonim", he: "ר' שמשון מאוסטרופולי", en: "Rabbi Shimshon of Ostropol",
    born: 1600, died: 1648, circa: true, region: "mizrachEurope", place: "אוסטרופול, פולין",
    w: "שמשון מאוסטרופולי", note: "מקובל נודע; נהרג על קידוש השם בגזירות ת\"ח ות\"ט.",
    books: [{ y: 1648, he: "דן ידין (פירוש קבלי)", en: "Dan Yadin (kabbalistic comm.)" }],
  },
  {
    era: "acharonim", he: "האלשיך (ר' משה אלשיך)", en: "Alshich (Moshe Alshich)",
    born: 1508, died: 1593, circa: true, region: "eretzIsrael", place: "אדריאנופול → צפת",
    w: "משה אלשיך", note: "מחכמי צפת ותלמיד מרן הבית יוסף; דרשן ופרשן — \"האלשיך הקדוש\", בעל הפירוש \"תורת משה\" על התנ\"ך.",
    books: [{ y: 1593, he: "תורת משה (פירוש האלשיך)", en: "Torat Moshe (Bible commentary)" }],
  },
  {
    era: "acharonim", he: "רמ\"ק (משה קורדובירו)", en: "Ramak (Moshe Cordovero)",
    born: 1522, died: 1570, region: "eretzIsrael", place: "צפת, ארץ ישראל",
    w: "משה קורדובירו", note: "ממסדרי הקבלה לפני האר\"י; שיטה עיונית בחכמת הסוד.",
    books: [{ y: 1548, he: "פרדס רמונים / תומר דבורה", en: "Pardes Rimonim; Tomer Devorah" }],
  },
  {
    era: "acharonim", he: "ספר חרדים (אלעזר אזכרי)", en: "Sefer Charedim (Elazar Azikri)",
    born: 1533, died: 1600, region: "eretzIsrael", place: "צפת, ארץ ישראל",
    w: "אלעזר אזכרי", note: "מקובל מחכמי צפת; ספר מוסר ויראה, וכתב את הפיוט \"ידיד נפש\".",
    books: [{ y: 1601, he: "ספר חרדים", en: "Sefer Charedim" }],
  },
  {
    era: "acharonim", he: "שיטה מקובצת (בצלאל אשכנזי)", en: "Shita Mekubetzet (Bezalel Ashkenazi)",
    born: 1520, died: 1592, circa: true, region: "eretzIsrael", place: "מצרים → ירושלים",
    w: "בצלאל אשכנזי", note: "ראש רבני מצרים ולימים ירושלים, ורבו של האר\"י; ליקט ב\"שיטה מקובצת\" את פירושי הראשונים על הש\"ס.",
    books: [{ y: 1580, he: "שיטה מקובצת", en: "Shita Mekubetzet (Talmud anthology)" }],
  },
  {
    era: "acharonim", he: "האר\"י (יצחק לוריא)", en: "Arizal (Isaac Luria)",
    born: 1534, died: 1572, region: "eretzIsrael", place: "ירושלים → צפת",
    w: "האר\"י", note: "אבי הקבלה הלוריאנית; נכתבה ע\"י תלמידיו.",
    books: [{ y: 1572, he: "כתבי האר\"י (עץ חיים)", en: "Lurianic Kabbalah (Etz Chaim)" }],
  },
  {
    era: "acharonim", he: "הב\"ח (יואל סירקיש)", en: "Bach (Yoel Sirkis)",
    born: 1561, died: 1640, region: "mizrachEurope", place: "לובלין → קרקוב",
    w: "יואל סירקיש", note: "מחשובי האחרונים; פירושו על הטור, וחותנו של הט\"ז.",
    books: [{ y: 1631, he: "בית חדש (ב\"ח) על הטור", en: "Bayit Chadash (Bach) on the Tur" }],
  },
  {
    era: "acharonim", he: "ט\"ז (דוד הלוי סגל)", en: "Taz (David HaLevi Segal)",
    born: 1586, died: 1667, region: "mizrachEurope", place: "קרקוב → לבוב",
    w: "דוד הלוי סגל", note: "מן הפרשנים המרכזיים של השולחן ערוך.",
    books: [{ y: 1646, he: "טורי זהב (ט\"ז)", en: "Turei Zahav (on Shulchan Aruch)" }],
  },
  {
    era: "acharonim", he: "ש\"ך (שבתי הכהן)", en: "Shach (Shabtai HaKohen)",
    born: 1621, died: 1662, region: "mizrachEurope", place: "וילנה → הולשוב",
    w: "שבתי כהן", note: "מן הפרשנים המרכזיים של השולחן ערוך.",
    books: [{ y: 1646, he: "שפתי כהן (ש\"ך)", en: "Siftei Kohen (commentary on Shulchan Aruch)" }],
  },
  {
    era: "acharonim", he: "ר' נפתלי כ\"ץ (סמיכת חכמים)", en: "Naftali Katz (Semichat Chachamim)",
    born: 1649, died: 1718, region: "merkazEurope", place: "פוזן → פרנקפורט",
    w: "נפתלי כ\"ץ", note: "מקובל ופוסק; רבן של פוזן ופרנקפורט.",
    books: [{ y: 1704, he: "סמיכת חכמים", en: "Semichat Chachamim" }],
  },
  {
    era: "acharonim", he: "כנסת הגדולה (חיים בנבנישתי)", en: "Knesset HaGedolah (Chaim Benveniste)",
    born: 1603, died: 1673, region: "turkiya", place: "קושטא → איזמיר, תורכיה",
    w: "חיים בנבנישתי", note: "מגדולי פוסקי הספרדים; אסף וסיכם את ההלכה שאחר הבית יוסף.",
    books: [{ y: 1658, he: "כנסת הגדולה", en: "Knesset HaGedolah" }],
  },
  {
    era: "acharonim", he: "שבט מוסר (אליהו הכהן האתמרי)", en: "Shevet Mussar (Eliyahu HaKohen)",
    born: 1650, died: 1729, circa: true, region: "turkiya", place: "איזמיר, תורכיה",
    w: "אליהו הכהן האתמרי", note: "דרשן ומחבר ספרי מוסר נפוצים.",
    books: [{ y: 1712, he: "שבט מוסר", en: "Shevet Mussar" }],
  },
  {
    era: "acharonim", he: "פלא יועץ (אליעזר פאפו)", en: "Pele Yoetz (Eliezer Papo)",
    born: 1785, died: 1828, region: "sefarad", place: "סרייבו → סיליסטרה",
    w: "אליעזר פאפו", note: "מחבר ספר מוסר ספרדי אהוב ונפוץ, ערוך לפי א\"ב.",
    books: [{ y: 1824, he: "פלא יועץ", en: "Pele Yoetz" }],
  },
  {
    era: "acharonim", he: "מחצית השקל (שמואל קעלין)", en: "Machatzit HaShekel (Shmuel Kelin)",
    born: 1720, died: 1806, region: "merkazEurope", place: "בוסקוביץ, מורביה",
    w: "שמואל קעלין", note: "מבארי הלכה; פירושו על המגן אברהם נדפס בשולחן ערוך.",
    books: [{ y: 1807, he: "מחצית השקל", en: "Machatzit HaShekel" }],
  },
  {
    era: "acharonim", he: "מגן אברהם", en: "Magen Avraham (Avraham Gombiner)",
    born: 1635, died: 1682, region: "mizrachEurope", place: "קאליש, פולין",
    w: "אברהם אבלי גומבינר", note: "פרשן מרכזי על אורח חיים.",
    books: [{ y: 1671, he: "מגן אברהם", en: "Magen Avraham (on Orach Chaim)" }],
  },
  {
    era: "acharonim", he: "פני יהושע (יעקב יהושע פלק)", en: "Pnei Yehoshua (Yaakov Yehoshua Falk)",
    born: 1680, died: 1756, region: "merkazEurope", place: "קרקוב → פרנקפורט",
    w: "יעקב יהושע פלק", note: "מגדולי מפרשי התלמוד; עיון מעמיק בסוגיות הש\"ס.",
    books: [{ y: 1739, he: "פני יהושע", en: "Pnei Yehoshua (Talmudic novellae)" }],
  },
  {
    era: "acharonim", he: "משנה למלך (יהודה רוזאניס)", en: "Mishneh LaMelech (Judah Rosanes)",
    born: 1657, died: 1727, region: "turkiya", place: "קושטא",
    w: "יהודה רוזאניס", note: "רבה של קושטא ומגדולי הפוסקים; חיבוריו \"משנה למלך\" על הרמב\"ם ו\"פרשת דרכים\" יצאו לאור בידי תלמידו בעל \"מעם לועז\".",
    books: [{ y: 1731, he: "משנה למלך / פרשת דרכים", en: "Mishneh LaMelech; Parashat Derachim" }],
  },
  {
    era: "acharonim", he: "מעם לועז (ר' יעקב כולי)", en: "Me'am Lo'ez (Yaakov Culi)",
    born: 1689, died: 1732, circa: true, region: "turkiya", place: "ירושלים → קושטא",
    w: "יעקב כולי", note: "דיין בקושטא; יזם וכתב את \"מעם לועז\" — חיבור פרשני־הלכתי בלאדינו להמון העם.",
    books: [{ y: 1730, he: "מעם לועז", en: "Me'am Lo'ez (Ladino Torah anthology)" }],
  },
  {
    era: "acharonim", he: "אור החיים (חיים בן עטר)", en: "Ohr HaChaim (Chaim ibn Attar)",
    born: 1696, died: 1743, region: "tzfonAfrica", place: "מרוקו → ירושלים",
    w: "חיים בן עטר", note: "פרשן ומקובל; \"אור החיים הקדוש\".",
    books: [{ y: 1742, he: "אור החיים על התורה", en: "Ohr HaChaim (Torah commentary)" }],
  },
  {
    era: "acharonim", he: "הרש\"ש (ר' שלום שרעבי)", en: "Rashash (Shalom Sharabi)",
    born: 1720, died: 1777, circa: true, region: "eretzIsrael", place: "תימן → ירושלים",
    w: "שלום שרעבי", note: "מקובל יליד תימן שעמד בראש ישיבת המקובלים \"בית אל\" בירושלים; מגדולי מפרשי כתבי האר\"י, בעל \"נהר שלום\" וסידור הכוונות.",
    books: [{ y: 1770, he: "נהר שלום / סידור הרש\"ש", en: "Nahar Shalom; Siddur HaRashash" }],
  },
  {
    era: "acharonim", he: "החיד\"א (חיים יוסף דוד אזולאי)", en: "Chida (Chaim Yosef David Azulai)",
    born: 1724, died: 1806, region: "eretzIsrael", place: "ירושלים → ליבורנו",
    w: "חיים יוסף דוד אזולאי", note: "פוסק, מקובל וביבליוגרף ספרדי; שליח ונוסע גדול.",
    books: [{ y: 1774, he: "שם הגדולים / ברכי יוסף", en: "Shem ha-Gedolim; Birkei Yosef" }],
  },
  {
    era: "acharonim", he: "רמח\"ל (משה חיים לוצאטו)", en: "Ramchal (Moshe Chaim Luzzatto)",
    born: 1707, died: 1746, region: "italia", place: "פדואה, איטליה → עכו",
    w: "רמח\"ל", note: "מקובל, הוגה דעות ומשורר; חיבר את ספר המוסר \"מסילת ישרים\".",
    books: [{ y: 1740, he: "מסילת ישרים", en: "Mesillat Yesharim" }],
  },
  {
    era: "acharonim", he: "ר' יהונתן אייבשיץ", en: "Rabbi Jonathan Eybeschutz",
    born: 1690, died: 1764, region: "merkazEurope", place: "פראג → אלטונה",
    w: "יהונתן אייבשיץ", note: "מגדולי הפלפול והפסיקה; פרשת הקמיעות והפולמוס עם היעב\"ץ.",
    books: [{ y: 1775, he: "אורים ותומים / כריתי ופליתי", en: "Urim ve-Tumim; Kreiti u-Pleiti" }],
  },
  {
    era: "acharonim", he: "ר' יעקב עמדין (יעב\"ץ)", en: "Rabbi Jacob Emden (Yavetz)",
    born: 1697, died: 1776, region: "ashkenaz", place: "אלטונה, אשכנז",
    w: "יעקב עמדין", note: "פוסק וחוקר; נאבק בשבתאות ובפולמוס עם ר' יהונתן אייבשיץ.",
    books: [{ y: 1745, he: "שאילת יעב\"ץ / סידור היעב\"ץ", en: "She'ilat Yavetz; Siddur Yavetz" }],
  },
  {
    era: "acharonim", he: "באר היטב (יהודה אשכנזי)", en: "Be'er Heitev (Yehuda Ashkenazi)",
    born: 1700, died: 1770, circa: true, region: "mizrachEurope", place: "טיקטין, פולין",
    w: "יהודה אשכנזי (טיקטין)", note: "דיין בטיקטין; פירוש מלקט ונפוץ על השולחן ערוך.",
    books: [{ y: 1742, he: "באר היטב", en: "Be'er Heitev (on Shulchan Aruch)" }],
  },
  {
    era: "chassidut", he: "בעל שם טוב (בעש\"ט)", en: "Baal Shem Tov",
    born: 1698, died: 1760, region: "mizrachEurope", place: "מז'יבוז', אוקראינה",
    w: "ישראל בעל שם טוב", note: "מייסד תנועת החסידות.",
    books: [{ y: 1781, he: "כתר שם טוב (תורתו)", en: "Founder of Chassidut (teachings)" }],
  },
  {
    era: "chassidut", he: "המגיד ממזריטש", en: "Maggid of Mezeritch (Dov Ber)",
    born: 1704, died: 1772, circa: true, region: "mizrachEurope", place: "מזריטש, אוקראינה",
    w: "המגיד ממזריטש", note: "ממשיכו של הבעש\"ט; הפיץ את החסידות וגידל את מנהיגי הדור הבא.",
    books: [{ y: 1781, he: "מגיד דבריו ליעקב", en: "Maggid Devarav le-Yaakov" }],
  },
  {
    era: "chassidut", he: "תולדות יעקב יוסף (יעקב יוסף מפולנאה)", en: "Toldot Yaakov Yosef (Yaakov Yosef of Polonne)",
    born: 1710, died: 1784, circa: true, region: "mizrachEurope", place: "פולנאה, אוקראינה",
    w: "יעקב יוסף כ\"ץ", note: "מבכירי תלמידי הבעש\"ט; ספרו הוא הספר החסידי הראשון בדפוס.",
    books: [{ y: 1780, he: "תולדות יעקב יוסף", en: "Toldot Yaakov Yosef" }],
  },
  {
    era: "chassidut", he: "ר' אלימלך מליז'ענסק", en: "Rabbi Elimelech of Lizhensk",
    born: 1717, died: 1787, region: "mizrachEurope", place: "ליז'נסק, גליציה",
    w: "אלימלך מליז'נסק", note: "מתלמידי המגיד ממזריטש; מאבות החסידות בפולין וגליציה.",
    books: [{ y: 1788, he: "נועם אלימלך", en: "No'am Elimelech" }],
  },
  {
    era: "chassidut", he: "ר' זושא מאניפולי", en: "Rabbi Zusha of Anipoli",
    born: 1718, died: 1800, circa: true, region: "mizrachEurope", place: "אניפולי, אוקראינה",
    w: "משולם זושא מאניפולי", note: "מתלמידי המגיד ממזריטש; אחיו של ר' אלימלך, מופת לעבודת ה' בתמימות.",
    books: [],
  },
  {
    era: "chassidut", he: "המגיד מזלוטשוב", en: "Maggid of Zlotchov (Yechiel Michel)",
    born: 1721, died: 1786, circa: true, region: "mizrachEurope", place: "זלוטשוב, גליציה",
    w: "יחיאל מיכל מזלוטשוב", note: "מתלמידי הבעש\"ט והמגיד ממזריטש; מאבות החסידות בגליציה.",
    books: [],
  },
  {
    era: "chassidut", he: "ר' פנחס מקוריץ", en: "Rabbi Pinchas of Koretz",
    born: 1726, died: 1790, region: "mizrachEurope", place: "קוריץ, אוקראינה",
    w: "פנחס שפירא מקוריץ", note: "מתלמידי-חבריו של הבעש\"ט; נודע במידת האמת.",
    books: [{ y: 1872, he: "מדרש פנחס / נופת צופים", en: "Midrash Pinchas; Nofet Tzufim" }],
  },
  {
    era: "chassidut", he: "מאור עיניים (מנחם נחום מטשרנוביל)", en: "Me'or Einayim (Menachem Nachum of Chernobyl)",
    born: 1730, died: 1797, circa: true, region: "mizrachEurope", place: "טשרנוביל, אוקראינה",
    w: "מנחם נחום מצ'רנוביל", note: "מתלמידי הבעש\"ט והמגיד; אבי שושלת טשרנוביל.",
    books: [{ y: 1798, he: "מאור עיניים", en: "Me'or Einayim" }],
  },
  {
    era: "chassidut", he: "ר' מנחם מנדל מוויטבסק", en: "Menachem Mendel of Vitebsk",
    born: 1730, died: 1788, region: "eretzIsrael", place: "ויטבסק → טבריה",
    w: "מנחם מנדל מוויטבסק", note: "מבכירי תלמידי המגיד ממזריטש; הנהיג את עליית החסידים לארץ ישראל (תקל\"ז) והתיישב בטבריה.",
    books: [{ y: 1814, he: "פרי הארץ", en: "Pri ha-Aretz" }],
  },
  {
    era: "acharonim", he: "יסוד ושורש העבודה (אלכסנדר זיסקינד)", en: "Yesod veShoresh HaAvodah (Alexander Ziskind)",
    born: 1720, died: 1794, circa: true, region: "mizrachEurope", place: "הורודנא (גרודנו), ליטא",
    w: "יסוד ושורש העבודה", note: "ספר יסוד בעבודת ה' והכוונה בתפילה.",
    books: [{ y: 1782, he: "יסוד ושורש העבודה", en: "Yesod veShoresh HaAvodah" }],
  },
  {
    era: "chassidut", he: "ר' אהרן הגדול מקרלין", en: "Aharon of Karlin (I)",
    born: 1736, died: 1772, region: "mizrachEurope", place: "קרלין, ליטא",
    w: "אהרן הגדול מקרלין", note: "מבכירי תלמידי המגיד ממזריטש ומאבות החסידות בליטא; מייסד שושלת קרלין וכתב את הפיוט \"יה אכסוף\".",
    books: [],
  },
  {
    era: "chassidut", he: "המגיד מקוז'ניץ", en: "Maggid of Kozhnitz (Yisrael Hopstein)",
    born: 1737, died: 1814, region: "mizrachEurope", place: "קוז'ניץ, פולין",
    w: "ישראל הופשטיין מקוז'ניץ", note: "מתלמידי המגיד ממזריטש ור' אלימלך; ממנהיגי החסידות בפולין.",
    books: [{ y: 1798, he: "עבודת ישראל", en: "Avodat Yisrael" }],
  },
  {
    era: "chassidut", he: "ר' לוי יצחק מברדיטשוב", en: "Rabbi Levi Yitzchok of Berditchev",
    born: 1740, died: 1809, region: "mizrachEurope", place: "ברדיטשוב, אוקראינה",
    w: "לוי יצחק מברדיצ'ב", note: "מתלמידי המגיד ממזריטש; \"סנגורן של ישראל\".",
    books: [{ y: 1798, he: "קדושת לוי", en: "Kedushat Levi" }],
  },
  {
    era: "acharonim", he: "המגיד מדובנא", en: "Maggid of Dubno (Yaakov Kranz)",
    born: 1741, died: 1804, region: "mizrachEurope", place: "דובנא, ווהלין",
    w: "יעקב קרנץ", note: "מגדולי הדרשנים; נודע במשליו המחכימים.",
    books: [{ y: 1799, he: "אוהל יעקב", en: "Ohel Yaakov (parables)" }],
  },
  {
    era: "chassidut", he: "החוזה מלובלין", en: "Chozeh of Lublin (Yaakov Yitzchak Horowitz)",
    born: 1745, died: 1815, region: "mizrachEurope", place: "לובלין, פולין",
    w: "יעקב יצחק הורוביץ", note: "מתלמידי ר' אלימלך; \"החוזה\" שהעמיד את גדולי חסידות פולין.",
    books: [{ y: 1851, he: "דברי אמת / זאת זכרון", en: "Divrei Emet; Zot Zikaron" }],
  },
  {
    era: "chassidut", he: "האוהב ישראל מאפטא", en: "Apta Rav (Avraham Yehoshua Heschel)",
    born: 1748, died: 1825, region: "mizrachEurope", place: "אפטא → מז'יבוז'",
    w: "אברהם יהושע השיל מאפטא", note: "מצדיקי הדור; נודע בשם ספרו \"אוהב ישראל\".",
    books: [{ y: 1863, he: "אוהב ישראל", en: "Ohev Yisrael" }],
  },
  {
    era: "chassidut", he: "היהודי הקדוש מפשיסחה", en: "The Holy Jew of Peshischa",
    born: 1766, died: 1813, region: "mizrachEurope", place: "פשיסחה, פולין",
    w: "יעקב יצחק מפשיסחה", note: "תלמיד החוזה מלובלין; מייסד דרך פשיסחה שהדגישה עבודה פנימית ועיון.",
    books: [{ y: 1908, he: "תורת היהודי הקדוש", en: "Teachings of the Holy Jew" }],
  },
  {
    era: "chassidut", he: "אהבת שלום מקוסוב", en: "Ahavat Shalom of Kosov (Menachem Mendel Hager)",
    born: 1768, died: 1825, region: "mizrachEurope", place: "קוסוב, גליציה",
    w: "מנחם מנדל הגר (קוסוב)", note: "מייסד שושלת קוסוב-ויז'ניץ; נודע בשם ספרו \"אהבת שלום\".",
    books: [{ y: 1833, he: "אהבת שלום", en: "Ahavat Shalom" }],
  },
  {
    era: "chassidut", he: "ישמח משה (משה טייטלבוים)", en: "Yismach Moshe (Moshe Teitelbaum)",
    born: 1759, died: 1841, region: "merkazEurope", place: "אוהל, הונגריה",
    w: "משה טייטלבוים (ישמח משה)", note: "מאבות החסידות בהונגריה; אבי שושלת סיגט-סאטמר.",
    books: [{ y: 1849, he: "ישמח משה", en: "Yismach Moshe" }],
  },
  {
    era: "chassidut", he: "ר' ישראל מרוז'ין", en: "Rabbi Israel of Ruzhin",
    born: 1796, died: 1850, region: "mizrachEurope", place: "רוז'ין → סדיגורה",
    w: "ישראל פרידמן (רוז'ין)", note: "\"הקדוש מרוז'ין\"; מייסד שושלות רוז'ין-סדיגורה ובוהוש.",
    books: [{ y: 1864, he: "עירין קדישין", en: "Irin Kadishin" }],
  },
  {
    era: "chassidut", he: "ר' מאיר מפרמישלאן", en: "Rabbi Meir of Premishlan",
    born: 1783, died: 1850, region: "mizrachEurope", place: "פרמישלאן, גליציה",
    w: "מאיר מפרמישלאן", note: "צדיק ומופת בגליציה; נודע בפשטותו ובאהבת ישראל שלו.",
    books: [],
  },
  {
    era: "chassidut", he: "ר' נפתלי מרופשיץ", en: "Rabbi Naftali of Ropshitz",
    born: 1760, died: 1827, region: "mizrachEurope", place: "רופשיץ, גליציה",
    w: "נפתלי צבי הורוביץ", note: "מתלמידי החוזה מלובלין ור' אלימלך; אדמו\"ר נודע בחריפותו ובחידודו.",
    books: [{ y: 1868, he: "זרע קודש", en: "Zera Kodesh" }],
  },
  {
    era: "chassidut", he: "ר' צבי הירש מזידיטשוב", en: "Rabbi Tzvi Hirsh of Zidichov",
    born: 1763, died: 1831, region: "mizrachEurope", place: "זידיטשוב, גליציה",
    w: "צבי הירש מזידיטשוב", note: "מתלמידי החוזה מלובלין; מקובל ומייסד שושלת זידיטשוב.",
    books: [{ y: 1834, he: "סור מרע ועשה טוב / עטרת צבי", en: "Sur me-Ra; Ateret Tzvi" }],
  },
  {
    era: "chassidut", he: "השר שלום מבעלזא", en: "Sar Shalom of Belz (Shalom Rokeach)",
    born: 1779, died: 1855, region: "mizrachEurope", place: "בעלזא, גליציה",
    w: "שלום רוקח", note: "מייסד שושלת בעלז; מגדולי האדמו\"רים בגליציה.",
    books: [],
  },
  {
    era: "chassidut", he: "בני יששכר (צבי אלימלך שפירא)", en: "Bnei Yissaschar (Tzvi Elimelech Spira)",
    born: 1783, died: 1841, region: "mizrachEurope", place: "דינוב, גליציה",
    w: "צבי אלימלך שפירא", note: "אדמו\"ר ומקובל; נודע בשם ספרו על המועדים \"בני יששכר\".",
    books: [{ y: 1846, he: "בני יששכר", en: "Bnei Yissaschar" }],
  },
  {
    era: "chassidut", he: "ר' מנחם מנדל מקוצק", en: "Menachem Mendel of Kotzk",
    born: 1787, died: 1859, region: "mizrachEurope", place: "קוצק, פולין",
    w: "מנחם מנדל מקוצק", note: "מגדולי תלמידי פשיסחא; \"הקוצקער\" הנודע בחריפותו, בחתירה לאמת ובהסתגרותו בשנותיו האחרונות.",
    books: [],
  },
  {
    era: "chassidut", he: "דברי חיים מצאנז", en: "Divrei Chaim of Sanz (Chaim Halberstam)",
    born: 1793, died: 1876, region: "mizrachEurope", place: "צאנז, גליציה",
    w: "חיים הלברשטאם", note: "מייסד שושלת צאנז; פוסק ואדמו\"ר רב-השפעה.",
    books: [{ y: 1864, he: "דברי חיים (שו\"ת)", en: "Divrei Chaim (responsa)" }],
  },
  {
    era: "chassidut", he: "חידושי הרי\"ם (יצחק מאיר מגור)", en: "Chiddushei HaRim (Yitzchak Meir Alter)",
    born: 1799, died: 1866, region: "mizrachEurope", place: "גור, פולין",
    w: "יצחק מאיר אלתר", note: "מתלמידי הקוצקער ומייסד שושלת גור; מגדולי הלמדנים, בעל \"חידושי הרי\"ם\" על הש\"ס והשו\"ע.",
    books: [{ y: 1865, he: "חידושי הרי\"ם", en: "Chiddushei HaRim" }],
  },
  {
    era: "chassidut", he: "רבי צדוק הכהן מלובלין", en: "Tzadok HaKohen of Lublin",
    born: 1823, died: 1900, region: "mizrachEurope", place: "לובלין, פולין",
    w: "צדוק הכהן מלובלין", note: "אדמו\"ר והוגה דעות; חיבר ספרי מחשבה וחסידות עמוקים, ובהם \"צדקת הצדיק\" ו\"פרי צדיק\".",
    books: [{ y: 1902, he: "צדקת הצדיק / פרי צדיק", en: "Tzidkat ha-Tzaddik; Pri Tzaddik" }],
  },
  {
    era: "chassidut", he: "אבני נזר (אברהם מסוכטשוב)", en: "Avnei Nezer (Avraham Bornstein)",
    born: 1838, died: 1910, region: "mizrachEurope", place: "סוכטשוב, פולין",
    w: "אברהם בורנשטיין", note: "מייסד חסידות סוכטשוב וחתנו של הקוצקער; מגדולי הלמדנים, בעל שו\"ת \"אבני נזר\" ו\"אגלי טל\".",
    books: [{ y: 1912, he: "שו\"ת אבני נזר / אגלי טל", en: "Avnei Nezer (responsa); Eglei Tal" }],
  },
  {
    era: "chassidut", he: "שפת אמת (מגור)", en: "Sfas Emes (Yehudah Aryeh Leib Alter)",
    born: 1847, died: 1905, region: "mizrachEurope", place: "גור, פולין",
    w: "יהודה אריה ליב אלתר", note: "האדמו\"ר השני בשושלת גור; מספריו היסודיים בחסידות ובש\"ס.",
    books: [{ y: 1905, he: "שפת אמת", en: "Sfas Emes" }],
  },
  {
    era: "chassidut", he: "מנחת אלעזר (חיים אלעזר שפירא ממונקאטש)", en: "Minchas Elazar (Chaim Elazar Spira of Munkacs)",
    born: 1868, died: 1937, region: "merkazEurope", place: "מונקאטש, הונגריה",
    w: "חיים אלעזר שפירא", note: "האדמו\"ר ממונקאטש; פוסק, מקובל ולוחם נחרץ נגד הציונות, בעל שו\"ת \"מנחת אלעזר\".",
    books: [{ y: 1902, he: "שו\"ת מנחת אלעזר", en: "Minchas Elazar (responsa)" }],
  },
  {
    era: "chassidut", he: "ר' יואל טייטלבוים (סאטמר)", en: "Yoel Teitelbaum (Satmar Rav)",
    born: 1887, died: 1979, region: "usa", place: "סאטמר, הונגריה → ניו יורק",
    w: "יואל טייטלבוים", note: "מייסד חסידות סאטמר ומגדולי מנהיגיה; מחבר \"ויואל משה\".",
    books: [{ y: 1961, he: "ויואל משה / דברי יואל", en: "Vayoel Moshe; Divrei Yoel" }],
  },
  {
    era: "chassidut", he: "הרבי מליובאוויטש (מנחם מנדל שניאורסון)", en: "Lubavitcher Rebbe (Menachem Mendel Schneerson)",
    born: 1902, died: 1994, region: "usa", place: "רוסיה → ניו יורק",
    w: "מנחם מנדל שניאורסון", note: "האדמו\"ר השביעי של חב\"ד; הפך את התנועה לרשת עולמית של שליחות והפצת יהדות.",
    books: [{ y: 1980, he: "לקוטי שיחות / אגרות קודש", en: "Likkutei Sichot; Igrot Kodesh" }],
  },
  {
    era: "acharonim", he: "נודע ביהודה (יחזקאל לנדא)", en: "Noda BiYehuda (Yechezkel Landau)",
    born: 1713, died: 1793, region: "merkazEurope", place: "פראג, בוהמיה",
    w: "יחזקאל לנדא", note: "מגדולי הפוסקים; שו\"ת רב-השפעה.",
    books: [{ y: 1776, he: "נודע ביהודה (שו\"ת)", en: "Noda BiYehuda (responsa)" }],
  },
  {
    era: "acharonim", he: "הפלאה (פנחס הלוי הורוביץ)", en: "Hafla'ah (Pinchas HaLevi Horowitz)",
    born: 1731, died: 1805, region: "merkazEurope", place: "פרנקפורט, אשכנז",
    w: "פנחס הורוביץ", note: "תלמיד המגיד ממזריטש ורבה של פרנקפורט; רבו של החת\"ם סופר.",
    books: [{ y: 1787, he: "ספר הפלאה (כתובות)", en: "Sefer ha-Hafla'ah" }],
  },
  {
    era: "acharonim", he: "ר' חיים צאנזר", en: "Chaim Tzanzer of Brody",
    born: 1720, died: 1783, region: "mizrachEurope", place: "צאנז → ברודי, גליציה",
    w: "חיים צאנזר", note: "גדול מקובלי \"הקלויז\" בברודי ובעל סמכות תורנית בגליציה; הנהיג חבורת מקובלים בדרך הסגפנות.",
    books: [],
  },
  {
    era: "acharonim", he: "הגר\"א (הגאון מווילנא)", en: "Vilna Gaon (Gra)",
    born: 1720, died: 1797, region: "mizrachEurope", place: "וילנה, ליטא",
    w: "הגאון מווילנה", note: "מנהיג הליטאים והמתנגדים; גאון בכל מקצועות התורה.",
    books: [{ y: 1780, he: "ביאורי הגר\"א", en: "Bi'urei ha-Gra (glosses)" }],
  },
  {
    era: "acharonim", he: "ר' חיים מוולוז'ין", en: "Rabbi Chaim of Volozhin",
    born: 1749, died: 1821, region: "mizrachEurope", place: "וולוז'ין, ליטא",
    w: "חיים מוולוז'ין", note: "תלמיד הגר\"א; ייסד את ישיבת וולוז'ין — אם הישיבות הליטאיות.",
    books: [{ y: 1824, he: "נפש החיים", en: "Nefesh ha-Chaim" }],
  },
  {
    era: "acharonim", he: "חיי אדם (אברהם דנציג)", en: "Chayei Adam (Avraham Danzig)",
    born: 1748, died: 1820, region: "mizrachEurope", place: "וילנה, ליטא",
    w: "אברהם דנציג", note: "מתלמידי בית מדרשו של הגר\"א; קיצור הלכתי נפוץ לאורח חיים.",
    books: [{ y: 1810, he: "חיי אדם / חכמת אדם", en: "Chayei Adam; Chochmat Adam" }],
  },
  {
    era: "chassidut", he: "בעל התניא (ר' שניאור זלמן)", en: "Baal HaTanya (Shneur Zalman)",
    born: 1745, died: 1812, region: "mizrachEurope", place: "לאדי, רוסיה",
    w: "שניאור זלמן מלאדי", note: "מייסד חסידות חב\"ד; \"אדמו\"ר הזקן\".",
    books: [{ y: 1797, he: "ספר התניא / שו\"ע הרב", en: "Tanya, Shulchan Aruch HaRav" }],
  },
  {
    era: "chassidut", he: "ר' נחמן מברסלב", en: "Rabbi Nachman of Breslov",
    born: 1772, died: 1810, region: "mizrachEurope", place: "ברסלב → אומן, אוקראינה",
    w: "נחמן מברסלב", note: "נין הבעש\"ט; מייסד חסידות ברסלב.",
    books: [{ y: 1808, he: "ליקוטי מוהר\"ן / סיפורי מעשיות", en: "Likutei Moharan; Tales" }],
  },
  {
    era: "acharonim", he: "קצות החושן (אריה לייב הלר)", en: "Ketzot HaChoshen (Aryeh Leib Heller)",
    born: 1745, died: 1812, region: "mizrachEurope", place: "סטרי, גליציה",
    w: "אריה לייב הלר", note: "מעמודי הלמדנות; חיבורו היסודי על חושן משפט.",
    books: [{ y: 1788, he: "קצות החושן", en: "Ketzot HaChoshen" }],
  },
  {
    era: "acharonim", he: "נתיבות המשפט (יעקב לורברבוים)", en: "Netivot HaMishpat (Yaakov Lorberbaum)",
    born: 1760, died: 1832, region: "mizrachEurope", place: "ליסא, פולין",
    w: "יעקב לורברבוים", note: "מבעלי הפלפול והפסיקה; בר-הפלוגתא של ה\"קצות\" על חושן משפט.",
    books: [{ y: 1809, he: "נתיבות המשפט", en: "Netivot HaMishpat" }],
  },
  {
    era: "acharonim", he: "מנחת חינוך (יוסף באב\"ד)", en: "Minchat Chinuch (Yosef Babad)",
    born: 1801, died: 1874, region: "mizrachEurope", place: "טרנופול, גליציה",
    w: "יוסף באב\"ד", note: "חיבור עיוני יסודי על תרי\"ג המצוות שבספר החינוך.",
    books: [{ y: 1869, he: "מנחת חינוך", en: "Minchat Chinuch" }],
  },
  {
    era: "acharonim", he: "שואל ומשיב (יוסף שאול נתנזון)", en: "Shoel uMeshiv (Yosef Shaul Nathansohn)",
    born: 1808, died: 1875, region: "mizrachEurope", place: "לבוב, גליציה",
    w: "יוסף שאול נתנזון", note: "מגדולי פוסקי גליציה; שו\"ת רב-היקף והשפעה.",
    books: [{ y: 1865, he: "שואל ומשיב (שו\"ת)", en: "Shoel uMeshiv (responsa)" }],
  },
  {
    era: "acharonim", he: "רש\"ר הירש", en: "Samson Raphael Hirsch",
    born: 1808, died: 1888, region: "ashkenaz", place: "המבורג → פרנקפורט, אשכנז",
    w: "רש\"ר הירש", note: "מנהיג היהדות האורתודוקסית בגרמניה ואבי גישת \"תורה עם דרך ארץ\"; פירוש מעמיק על התורה.",
    books: [{ y: 1867, he: "פירוש רש\"ר הירש על התורה / חורב", en: "Torah commentary; Horeb" }],
  },
  {
    era: "acharonim", he: "ר' שלמה קלוגר", en: "Rabbi Shlomo Kluger",
    born: 1785, died: 1869, region: "mizrachEurope", place: "ברודי, גליציה",
    w: "שלמה קלוגר", note: "מגדולי פוסקי גליציה; מחבר פורה במיוחד בהלכה ובדרוש.",
    books: [{ y: 1855, he: "חכמת שלמה / שו\"ת", en: "Chochmat Shlomo; responsa" }],
  },
  {
    era: "acharonim", he: "רבי עקיבא איגר", en: "Rabbi Akiva Eiger",
    born: 1761, died: 1837, region: "merkazEurope", place: "פוזן, פרוסיה",
    w: "עקיבא איגר", note: "מגדולי הפלפול והפסיקה.",
    books: [{ y: 1820, he: "שו\"ת ר' עקיבא איגר", en: "Responsa & Talmudic glosses" }],
  },
  {
    era: "acharonim", he: "ר' אפרים זלמן מרגליות (מטה אפרים)", en: "Ephraim Zalman Margolis (Mateh Ephraim)",
    born: 1762, died: 1828, region: "mizrachEurope", place: "ברודי, גליציה",
    w: "אפרים זלמן מרגליות", note: "פוסק וביבליוגרף; נודע בספרו על דיני אלול ותשרי.",
    books: [{ y: 1834, he: "מטה אפרים / בית אפרים", en: "Mateh Ephraim; Beit Ephraim" }],
  },
  {
    era: "acharonim", he: "חת\"ם סופר", en: "Chatam Sofer (Moshe Sofer)",
    born: 1762, died: 1839, region: "merkazEurope", place: "פרנקפורט → פרשבורג",
    w: "חת\"ם סופר", note: "מנהיג היהדות החרדית; \"חדש אסור מן התורה\".",
    books: [{ y: 1830, he: "שו\"ת חת\"ם סופר", en: "Chatam Sofer (responsa)" }],
  },
  {
    era: "acharonim", he: "קיצור שולחן ערוך (שלמה גאנצפריד)", en: "Kitzur Shulchan Aruch (Shlomo Ganzfried)",
    born: 1804, died: 1886, region: "merkazEurope", place: "אונגוואר, הונגריה",
    w: "שלמה גאנצפריד", note: "פוסק הונגרי; קיצור עממי ונפוץ של ההלכה למעשה.",
    books: [{ y: 1864, he: "קיצור שולחן ערוך", en: "Kitzur Shulchan Aruch" }],
  },
  {
    era: "acharonim", he: "ר' ישראל סלנטר", en: "Rabbi Yisrael Salanter",
    born: 1809, died: 1883, region: "mizrachEurope", place: "ליטא → גרמניה",
    w: "ישראל ליפקין מסלנט", note: "מייסד תנועת המוסר.",
    books: [{ y: 1858, he: "אגרת המוסר / תנועת המוסר", en: "Founder of the Mussar movement" }],
  },
  {
    era: "acharonim", he: "הסבא מקלם (שמחה זיסל זיו)", en: "Alter of Kelm (Simcha Zissel Ziv)",
    born: 1824, died: 1898, region: "mizrachEurope", place: "קלם, ליטא",
    w: "שמחה זיסל זיו", note: "מבכירי תלמידי ר' ישראל סלנטר; ייסד את ת\"ת קלם.",
    books: [{ y: 1900, he: "חכמה ומוסר", en: "Chochmah u-Mussar" }],
  },
  {
    era: "acharonim", he: "הרידב\"ז (יעקב דוד וילובסקי)", en: "Ridvaz (Yaakov Dovid Wilovsky)",
    born: 1845, died: 1913, region: "eretzIsrael", place: "ליטא → צפת",
    w: "יעקב דוד וילובסקי", note: "ראש ישיבה ופוסק ליטאי; כיהן ברבנות באירופה ובאמריקה ועלה לצפת, ונודע בפירושו על התלמוד הירושלמי.",
    books: [{ y: 1900, he: "פירוש הרידב\"ז על הירושלמי", en: "Commentary on the Jerusalem Talmud" }],
  },
  {
    era: "acharonim", he: "הסבא מנובהרדוק (יוסף יוזל הורוביץ)", en: "Alter of Novardok (Yosef Yozel Horwitz)",
    born: 1847, died: 1919, region: "mizrachEurope", place: "נובהרדוק, רוסיה",
    w: "יוסף יוזל הורוביץ", note: "תלמיד ר' ישראל סלנטר; ייסד את רשת ישיבות נובהרדוק.",
    books: [{ y: 1920, he: "מדרגת האדם", en: "Madregat ha-Adam" }],
  },
  {
    era: "acharonim", he: "הסבא מסלובודקה (נתן צבי פינקל)", en: "Alter of Slabodka (Nosson Tzvi Finkel)",
    born: 1849, died: 1927, region: "mizrachEurope", place: "סלובודקה → חברון",
    w: "נתן צבי פינקל", note: "מאדריכלי תנועת המוסר; ייסד את ישיבת סלובודקה ושיטת \"גדלות האדם\".",
    books: [{ y: 1924, he: "אור הצפון", en: "Ohr ha-Tzafun" }],
  },
  {
    era: "acharonim", he: "הנצי\"ב מוולוז'ין", en: "Netziv (Naftali Z. Y. Berlin)",
    born: 1816, died: 1893, region: "mizrachEurope", place: "וולוז'ין, ליטא",
    w: "נפתלי צבי יהודה ברלין", note: "ראש ישיבת וולוז'ין בשיאה; פרשן התורה והשאילתות.",
    books: [{ y: 1879, he: "העמק דבר / העמק שאלה", en: "Ha'amek Davar; Ha'amek She'elah" }],
  },
  {
    era: "acharonim", he: "ר' שמואל סלנט", en: "Rabbi Shmuel Salant",
    born: 1816, died: 1909, region: "eretzIsrael", place: "ביאליסטוק → ירושלים",
    w: "שמואל סלנט", note: "רבה של ירושלים כשבעים שנה; מבוני היישוב הישן.",
    books: [],
  },
  {
    era: "acharonim", he: "מהרי\"ל דיסקין", en: "Maharil Diskin (Yehoshua Leib Diskin)",
    born: 1818, died: 1898, region: "eretzIsrael", place: "בריסק → ירושלים",
    w: "משה יהושע יהודה לייב דיסקין", note: "מנהיג היישוב הישן בירושלים; ייסד את בית היתומים דיסקין.",
    books: [],
  },
  {
    era: "acharonim", he: "ר' יוסף חיים זוננפלד", en: "Yosef Chaim Sonnenfeld",
    born: 1848, died: 1932, region: "eretzIsrael", place: "סלובקיה → ירושלים",
    w: "יוסף חיים זוננפלד", note: "מתלמידי מהרי\"ל דיסקין; רבה של העדה החרדית ומנהיג היישוב הישן בירושלים.",
    books: [],
  },
  {
    era: "acharonim", he: "ר' חיים סולובייצ'יק (מבריסק)", en: "Rabbi Chaim Soloveitchik (Brisker)",
    born: 1853, died: 1918, region: "mizrachEurope", place: "וולוז'ין → בריסק",
    w: "חיים הלוי סולובייצ'יק", note: "מייסד \"דרך בריסק\" בלימוד הגמרא; ראש ישיבת וולוז'ין ורבה של בריסק.",
    books: [{ y: 1936, he: "חידושי רבנו חיים הלוי", en: "Chiddushei Rabbeinu Chaim HaLevi" }],
  },
  {
    era: "acharonim", he: "ר' שמעון שקופ", en: "Shimon Shkop",
    born: 1860, died: 1939, region: "mizrachEurope", place: "טלז → גרודנא",
    w: "שמעון שקופ", note: "מגדולי ראשי הישיבות ובעלי שיטת העיון הליטאית; ראש ישיבת גרודנא, בעל \"שערי יושר\".",
    books: [{ y: 1925, he: "שערי יושר / חידושי ר' שמעון", en: "Sha'arei Yosher" }],
  },
  {
    era: "acharonim", he: "ר' ברוך בר ליבוביץ", en: "Boruch Ber Leibowitz",
    born: 1864, died: 1939, region: "mizrachEurope", place: "סלובודקה → קמניץ",
    w: "ברוך בר ליבוביץ", note: "תלמידו המובהק של ר' חיים מבריסק; ראש ישיבת כנסת בית יצחק בקמניץ, בעל \"ברכת שמואל\".",
    books: [{ y: 1938, he: "ברכת שמואל", en: "Birkas Shmuel" }],
  },
  {
    era: "acharonim", he: "הגרי\"ז מבריסק", en: "Brisker Rav (Yitzchak Zeev Soloveitchik)",
    born: 1886, died: 1959, region: "eretzIsrael", place: "בריסק → ירושלים",
    w: "יצחק זאב הלוי סולובייצ'יק", note: "בנו של ר' חיים; ממשיך \"דרך בריסק\" וממנהיגי היהדות החרדית בארץ ישראל.",
    books: [{ y: 1963, he: "חידושי הגרי\"ז", en: "Chiddushei ha-Griz" }],
  },
  {
    era: "acharonim", he: "ערוך השולחן (י\"מ עפשטיין)", en: "Aruch HaShulchan (Y. M. Epstein)",
    born: 1829, died: 1908, region: "mizrachEurope", place: "נובהרדוק, רוסיה",
    w: "יחיאל מיכל הלוי אפשטיין", note: "קודיפיקציה שיטתית של ההלכה.",
    books: [{ y: 1884, he: "ערוך השולחן", en: "Aruch HaShulchan (halachic code)" }],
  },
  {
    era: "acharonim", he: "כף החיים (יעקב חיים סופר)", en: "Kaf HaChaim (Yaakov Chaim Sofer)",
    born: 1870, died: 1939, region: "eretzIsrael", place: "בגדאד → ירושלים",
    w: "יעקב חיים סופר", note: "פוסק ומקובל ספרדי; חיבורו היסודי על השולחן ערוך.",
    books: [{ y: 1905, he: "כף החיים", en: "Kaf HaChaim (on Shulchan Aruch)" }],
  },
  {
    era: "acharonim", he: "בן איש חי (יוסף חיים)", en: "Ben Ish Chai (Yosef Chaim)",
    born: 1835, died: 1909, region: "iraq", place: "בגדאד, עיראק",
    w: "יוסף חיים מבגדאד", note: "מנהיג יהדות בבל; הלכה וקבלה.",
    books: [{ y: 1898, he: "בן איש חי", en: "Ben Ish Chai (halacha & homily)" }],
  },
  {
    era: "acharonim", he: "חפץ חיים", en: "Chofetz Chaim (Yisrael Meir Kagan)",
    born: 1838, died: 1933, region: "mizrachEurope", place: "ראדין, פולין",
    w: "ישראל מאיר הכהן", note: "הלכות לשון הרע והמשנה ברורה.",
    books: [
      { y: 1873, he: "חפץ חיים (לשון הרע)", en: "Chofetz Chaim (laws of speech)" },
      { y: 1907, he: "משנה ברורה", en: "Mishnah Berurah (on Orach Chaim)" },
    ],
  },
  {
    era: "acharonim", he: "ר' חיים עוזר גרודזנסקי", en: "Rabbi Chaim Ozer Grodzinski",
    born: 1863, died: 1940, region: "mizrachEurope", place: "וילנה, ליטא",
    w: "חיים עוזר גרודזנסקי", note: "מנהיג יהדות ליטא; פוסק ועומד בראש ועד הישיבות.",
    books: [{ y: 1922, he: "אחיעזר (שו\"ת)", en: "Achiezer (responsa)" }],
  },
  {
    era: "acharonim", he: "ר' מאיר שפירא מלובלין", en: "Rabbi Meir Shapiro of Lublin",
    born: 1887, died: 1933, region: "mizrachEurope", place: "לובלין, פולין",
    w: "מאיר שפירא", note: "מייסד ישיבת חכמי לובלין; הוגה תקנת \"הדף היומי\".",
    books: [],
  },
  {
    era: "acharonim", he: "הראי\"ה קוק", en: "Rav A. I. Kook",
    born: 1865, died: 1935, region: "eretzIsrael", place: "לטביה → ירושלים",
    w: "אברהם יצחק הכהן קוק", note: "הרב הראשי הראשון לארץ ישראל; הוגה דעות.",
    books: [{ y: 1920, he: "אורות / אורות התשובה", en: "Orot, Orot HaTeshuvah" }],
  },
  {
    era: "acharonim", he: "ר' איסר זלמן מלצר", en: "Isser Zalman Meltzer",
    born: 1870, died: 1953, region: "eretzIsrael", place: "סלוצק → ירושלים",
    w: "איסר זלמן מלצר", note: "מגדולי ראשי הישיבות הליטאים; ראש ישיבת \"עץ חיים\" בירושלים, בעל \"אבן האזל\" על הרמב\"ם.",
    books: [{ y: 1935, he: "אבן האזל", en: "Even ha-Azel (on Rambam)" }],
  },
  {
    era: "acharonim", he: "חזון איש (אברהם ישעיהו קרליץ)", en: "Chazon Ish (A. Y. Karelitz)",
    born: 1878, died: 1953, region: "eretzIsrael", place: "בלארוס → בני ברק",
    w: "אברהם ישעיהו קרליץ", note: "מנהיג הציבור החרדי-ליטאי בארץ ישראל.",
    books: [{ y: 1911, he: "חזון איש", en: "Chazon Ish (halachic works)" }],
  },
  {
    era: "acharonim", he: "הסטייפלר (יעקב ישראל קניבסקי)", en: "Steipler (Yaakov Yisrael Kanievsky)",
    born: 1899, died: 1985, region: "eretzIsrael", place: "הורנשטייפל → בני ברק",
    w: "יעקב ישראל קניבסקי", note: "מגדולי ראשי הישיבות ופוסקי הדור; מחבר \"קהילות יעקב\".",
    books: [{ y: 1935, he: "קהילות יעקב", en: "Kehilot Yaakov" }],
  },
  {
    era: "acharonim", he: "ר' משה פיינשטיין", en: "Rabbi Moshe Feinstein",
    born: 1895, died: 1986, region: "usa", place: "בלארוס → ניו יורק",
    w: "משה פיינשטיין", note: "מגדולי פוסקי ההלכה במאה ה-20.",
    books: [{ y: 1959, he: "אגרות משה (שו\"ת)", en: "Igrot Moshe (responsa)" }],
  },
  {
    era: "acharonim", he: "ר' אלעזר מנחם מן שך", en: "Rabbi Elazar Shach",
    born: 1899, died: 2001, region: "eretzIsrael", place: "ליטא → בני ברק",
    w: "אלעזר מנחם מן שך", note: "ראש ישיבת פוניבז' ומנהיג היהדות הליטאית בארץ; בעל \"אבי עזרי\" על הרמב\"ם.",
    books: [{ y: 1952, he: "אבי עזרי", en: "Avi Ezri (on Rambam)" }],
  },
  {
    era: "acharonim", he: "ר' יוסף שלום אלישיב", en: "Rabbi Yosef Shalom Elyashiv",
    born: 1910, died: 2012, region: "eretzIsrael", place: "ירושלים",
    w: "יוסף שלום אלישיב", note: "מגדולי פוסקי הדור ומנהיג הציבור הליטאי בארץ ישראל.",
    books: [{ y: 2000, he: "קובץ תשובות / הערות", en: "Kovetz Teshuvot; Talmudic notes" }],
  },
  {
    era: "acharonim", he: "ר' שמואל הלוי ואזנר", en: "Rabbi Shmuel HaLevi Wosner",
    born: 1913, died: 2015, region: "eretzIsrael", place: "וינה → בני ברק",
    w: "שמואל הלוי ואזנר", note: "מגדולי הפוסקים בדורו; נודע בשם ספרו \"שבט הלוי\".",
    books: [{ y: 1958, he: "שבט הלוי (שו\"ת)", en: "Shevet HaLevi (responsa)" }],
  },
  {
    era: "acharonim", he: "הרב עובדיה יוסף", en: "Rabbi Ovadia Yosef",
    born: 1920, died: 2013, region: "eretzIsrael", place: "בגדאד → ירושלים",
    w: "עובדיה יוסף", note: "מגדולי פוסקי הדור ומנהיג יהדות ספרד; \"להחזיר עטרה ליושנה\".",
    books: [{ y: 1986, he: "יביע אומר / יחוה דעת", en: "Yabia Omer; Yechaveh Da'at" }],
  },
];

// Major world / Jewish-history events.
// j: true     → inner-Jewish history (not chiefly a world event)
// shift: true → a step in the migration of the Torah center from Bavel westward
const EVENTS = [
  { y: 70,   he: "חורבן בית שני", en: "Destruction of the Second Temple; Siege of Jerusalem", place: "ירושלים", w: "חורבן בית שני", j: true },
  { y: 73,   he: "נפילת מצדה", en: "Siege of Masada", place: "מצדה", w: "מצדה", j: true },
  { y: 132,  he: "מרד בר כוכבא", en: "Bar Kokhba revolt (132–135)", place: "ארץ ישראל", w: "מרד בר כוכבא", j: true },
  { y: 135,  he: "עשרת הרוגי מלכות; גזירות אדריאנוס", en: "Ten Martyrs; Hadrianic persecutions", place: "ארץ ישראל", w: "עשרת הרוגי מלכות", j: true },
  { y: 313,  he: "צו מילאנו — חופש דת לנצרות", en: "Edict of Milan", place: "האימפריה הרומית", w: "צו מילאנו" },
  { y: 325,  he: "ועידת ניקיאה", en: "First Council of Nicaea", place: "ניקיאה", w: "ועידת ניקיאה" },
  { y: 359,  he: "קביעת לוח השנה (הלל נשיאה)", en: "Hillel II fixes the Hebrew calendar", place: "ארץ ישראל", w: "הלל נשיאה", j: true },
  { y: 400,  he: "חתימת התלמוד הירושלמי", en: "Jerusalem Talmud redacted", place: "טבריה, ארץ ישראל", w: "תלמוד ירושלמי", j: true },
  { y: 476,  he: "נפילת האימפריה הרומית המערבית", en: "Fall of the Western Roman Empire", place: "רומא", w: "שקיעת האימפריה הרומית" },
  { y: 500,  he: "חתימת התלמוד הבבלי", en: "Babylonian Talmud sealed", place: "בבל", w: "תלמוד בבלי", j: true },
  { y: 529,  he: "קודקס יוסטיניאנוס", en: "Justinian's Code", place: "ביזנטיון", w: "קורפוס יוריס קיוויליס" },
  { y: 550,  he: "תקופת הסבוראים", en: "The Savoraim", place: "בבל", w: "סבוראים", j: true },
  { y: 622,  he: "עליית האסלאם (מוחמד)", en: "Rise of Islam; Muhammad's Hijra", place: "חצי האי ערב", w: "מוחמד" },
  { y: 638,  he: "הכיבוש הערבי של ארץ ישראל", en: "Arab conquest of the Land of Israel", place: "ירושלים", w: "הכיבוש הערבי של ארץ ישראל" },
  { y: 711,  he: "הכיבוש המוסלמי של ספרד", en: "Muslim conquest of Spain", place: "חצי האי האיברי", w: "הכיבוש המוסלמי של ספרד" },
  { y: 762,  he: "ייסוד בגדאד — בירת העבאסים", en: "Founding of Baghdad", place: "בגדאד, בבל", w: "בגדאד" },
  { y: 767,  he: "ראשית הקראות (ענן בן דוד)", en: "Anan ben David; Karaite schism", place: "בבל", w: "ענן בן דוד", j: true },
  { y: 800,  he: "קרל הגדול מוכתר לקיסר", en: "Charlemagne crowned Emperor", place: "אקס לה שאפל", w: "קרל הגדול" },
  { y: 942,  he: "שקיעת ישיבת סורא (רס\"ג)", en: "Death of Saadia Gaon; Sura declines", place: "בבל", w: "רב סעדיה גאון", shift: true },
  { y: 970,  he: "ארבעת השבויים — ייסוד ספרד", en: "Story of the Four Captives", place: "הים התיכון", w: "ארבעת השבויים", shift: true },
  { y: 1038, he: "סוף תקופת הגאונים", en: "End of the Geonic era", place: "בבל", w: "גאונים", shift: true },
  { y: 1088, he: "הרי\"ף עולה ללוסינה", en: "Rif moves to Lucena; Spain ascendant", place: "לוסינה, ספרד", w: "רי\"ף", shift: true },
  { y: 1096, he: "מסע הצלב הראשון; גזירות תתנ\"ו", en: "First Crusade; Rhineland massacres", place: "חבל הריין, אשכנז", w: "מסע הצלב הראשון", j: true },
  { y: 1099, he: "הצלבנים כובשים את ירושלים", en: "Crusaders capture Jerusalem", place: "ירושלים", w: "מצור ירושלים (1099)" },
  { y: 1147, he: "גזירות אל-מוואחידון", en: "Almohad persecutions; Maimonides' family flees", place: "ספרד וצפון אפריקה", w: "אל-מוואחידון", j: true },
  { y: 1171, he: "עלילת הדם בבלואה", en: "Blois blood libel", place: "בלואה, צרפת", w: "עלילת דם", j: true },
  { y: 1211, he: "עליית בעלי התוספות לארץ ישראל", en: "Aliyah of the Tosafists", place: "ארץ ישראל", w: "עליית בעלי התוספות", j: true },
  { y: 1215, he: "ועידת לטרנו הרביעית — אות הקלון ליהודים", en: "Fourth Lateran Council; the Jewish badge", place: "רומא", w: "ועידת לטראנו הרביעית" },
  { y: 1232, he: "פולמוס הרמב\"ם ושריפת ספריו", en: "Maimonidean Controversy; books burned", place: "פרובנס וצרפת", w: "פולמוס הרמב\"ם", j: true },
  { y: 1242, he: "שריפת התלמוד בפריז", en: "Burning of the Talmud in Paris", place: "פריז, צרפת", w: "שריפת התלמוד", j: true },
  { y: 1263, he: "ויכוח ברצלונה (הרמב\"ן)", en: "Disputation of Barcelona", place: "ברצלונה, ספרד", w: "ויכוח ברצלונה", j: true },
  { y: 1290, he: "גירוש היהודים מאנגליה", en: "Expulsion of Jews from England", place: "אנגליה", w: "גירוש יהודי אנגליה", j: true },
  { y: 1306, he: "גירוש היהודים מצרפת", en: "Expulsion of Jews from France", place: "צרפת", w: "גירוש צרפת הגדול", j: true },
  { y: 1348, he: "המוות השחור", en: "The Black Death", place: "אירופה", w: "המוות השחור" },
  { y: 1400, he: "הרנסאנס באיטליה", en: "The Renaissance", place: "פירנצה, איטליה", w: "רנסאנס" },
  { y: 1413, he: "ויכוח טורטוסה", en: "Disputation of Tortosa (1413–14)", place: "טורטוסה, ספרד", w: "ויכוח טורטוסה", j: true },
  { y: 1453, he: "נפילת קונסטנטינופול", en: "Fall of Constantinople", place: "קונסטנטינופול", w: "נפילת קונסטנטינופול" },
  { y: 1455, he: "דפוס גוטנברג", en: "Gutenberg's printing press", place: "מיינץ, אשכנז", w: "יוהאן גוטנברג" },
  { y: 1475, he: "הספר העברי הראשון בדפוס", en: "Hebrew incunabula; first printed book", place: "רג'ו די קלבריה, איטליה", w: "דפוס עברי", j: true },
  { y: 1478, he: "ייסוד האינקוויזיציה הספרדית", en: "Spanish Inquisition established", place: "ספרד", w: "האינקוויזיציה הספרדית" },
  { y: 1492, he: "גירוש ספרד; גילוי אמריקה", en: "Expulsion from Spain; Columbus", place: "ספרד", w: "גירוש ספרד", j: true },
  { y: 1497, he: "גירוש והמרת יהודי פורטוגל", en: "Forced conversion of Portugal's Jews", place: "פורטוגל", w: "הטבלת יהודי פורטוגל לנצרות", j: true },
  { y: 1516, he: "גטו ונציה — הראשון בעולם", en: "Venetian Ghetto established", place: "ונציה, איטליה", w: "גטו ונציה", j: true },
  { y: 1517, he: "הרפורמציה הפרוטסטנטית", en: "Protestant Reformation", place: "אשכנז", w: "הרפורמציה הפרוטסטנטית" },
  { y: 1565, he: "פרסום השולחן ערוך", en: "Publication of the Shulchan Aruch", place: "צפת וונציה", w: "שולחן ערוך", j: true },
  { y: 1580, he: "ועד ארבע ארצות", en: "Council of Four Lands convenes", place: "פולין", w: "ועד ארבע ארצות", j: true },
  { y: 1618, he: "מלחמת שלושים השנים", en: "Thirty Years' War (1618–48)", place: "מרכז אירופה", w: "מלחמת שלושים השנים" },
  { y: 1648, he: "גזירות ת\"ח ות\"ט", en: "Chmielnicki massacres", place: "אוקראינה ופולין", w: "גזירות ת\"ח ות\"ט", j: true },
  { y: 1666, he: "תנועת שבתי צבי", en: "Shabbetai Zevi messianic movement", place: "האימפריה העות'מאנית", w: "שבתי צבי", j: true },
  { y: 1683, he: "קרב וינה — בלימת העות'מאנים", en: "Battle of Vienna", place: "וינה", w: "קרב וינה" },
  { y: 1740, he: "ראשית החסידות (הבעש\"ט)", en: "Baal Shem Tov; rise of Hasidism", place: "פודוליה, מזרח אירופה", w: "חסידות", j: true },
  { y: 1760, he: "המהפכה התעשייתית", en: "Industrial Revolution", place: "אנגליה", w: "המהפכה התעשייתית" },
  { y: 1772, he: "מחלוקת חסידים ומתנגדים", en: "Misnagdim; Hasidic-Mitnagdic split", place: "וילנה, ליטא", w: "מתנגדים", j: true },
  { y: 1772, he: "חלוקת פולין הראשונה", en: "First Partition of Poland", place: "פולין", w: "חלוקת פולין" },
  { y: 1784, he: "תנועת ההשכלה (משה מנדלסון)", en: "Haskalah; Moses Mendelssohn", place: "ברלין, אשכנז", w: "תנועת ההשכלה היהודית", j: true },
  { y: 1789, he: "המהפכה הצרפתית", en: "French Revolution", place: "צרפת", w: "המהפכה הצרפתית" },
  { y: 1800, he: "וולטה ממציא את הסוללה החשמלית", en: "Volta's electric battery; harnessing electricity", place: "פאביה, איטליה", w: "אלסנדרו וולטה" },
  { y: 1807, he: "הסנהדרין של נפוליאון", en: "Grand Sanhedrin", place: "פריז, צרפת", w: "הסנהדרין של נפוליאון", j: true },
  { y: 1840, he: "עלילת דמשק", en: "Damascus Affair (blood libel)", place: "דמשק, סוריה", w: "עלילת דמשק", j: true },
  { y: 1859, he: "מוצא המינים (דרווין)", en: "Darwin's Origin of Species", place: "אנגליה", w: "מוצא המינים" },
  { y: 1881, he: "פרעות ברוסיה; ראשית העלייה", en: "Russian pogroms; First Aliyah", place: "תחום המושב, רוסיה", w: "העלייה הראשונה", j: true },
  { y: 1894, he: "פרשת דרייפוס", en: "Dreyfus Affair", place: "פריז, צרפת", w: "פרשת דרייפוס", j: true },
  { y: 1897, he: "הקונגרס הציוני הראשון", en: "First Zionist Congress", place: "באזל, שווייץ", w: "הקונגרס הציוני הראשון", j: true },
  { y: 1914, he: "מלחמת העולם הראשונה", en: "World War I (1914–18)", place: "אירופה", w: "מלחמת העולם הראשונה" },
  { y: 1917, he: "הצהרת בלפור", en: "Balfour Declaration", place: "לונדון, אנגליה", w: "הצהרת בלפור", j: true },
  { y: 1917, he: "המהפכה הרוסית", en: "Russian Revolution", place: "רוסיה", w: "המהפכה הרוסית" },
  { y: 1933, he: "עליית הנאצים לשלטון", en: "Nazis rise to power", place: "גרמניה", w: "עליית הנאצים לשלטון" },
  { y: 1939, he: "מלחמת העולם השנייה והשואה", en: "WWII & the Holocaust", place: "אירופה", w: "השואה", j: true },
  { y: 1948, he: "הקמת מדינת ישראל", en: "Establishment of the State of Israel", place: "ארץ ישראל", w: "הקמת מדינת ישראל", j: true },
];

// Authoritative en.wikipedia titles, pulled from each article's language
// switcher (he→en interlanguage links via the API). GENERATED — regenerate
// rather than hand-editing; keys are the `w` (he.wikipedia) titles. Entries
// without an English article fall back to search in app.js.
const WIKI_EN = {
  "רבן גמליאל הזקן": "Gamaliel",
  "רבן יוחנן בן זכאי": "Yohanan ben Zakkai",
  "רבי צדוק": "Rabbi Zadok",
  "רבי חנינא בן דוסא": "Hanina ben Dosa",
  "רבי אליעזר בן הורקנוס": "Eliezer ben Hurcanus",
  "רבי יהושע בן חנניה": "Joshua ben Hananiah",
  "רבי אלעזר בן ערך": "Eleazar ben Arach",
  "רבי אלעזר בן עזריה": "Eleazar ben Azariah",
  "רבי נחוניה בן הקנה": "Nehunya ben HaKanah",
  "רבן גמליאל דיבנה": "Gamaliel II",
  "רבי עקיבא": "Rabbi Akiva",
  "רבי יהודה בן בבא": "Judah ben Bava",
  "רבי ישמעאל": "Rabbi Ishmael",
  "רבי טרפון": "Rabbi Tarfon",
  "רבי יוסי הגלילי": "Jose the Galilean",
  "רבי יוחנן בן נורי": "Johanan ben Nuri",
  "רבי מאיר": "Rabbi Meir",
  "רבי יהודה": "Judah bar Ilai",
  "רבי יוסי בן קיסמא": "Jose ben Kisma",
  "רבי יוחנן הסנדלר": "Johanan HaSandlar",
  "רבי שמעון בר יוחאי": "Shimon bar Yochai",
  "רבי נתן": "Nathan the Babylonian",
  "רבי יהודה הנשיא": "Judah ha-Nasi",
  "רבי חייא": "Hiyya the Great",
  "בר קפרא": "Bar Kappara",
  "רבי אושעיא": "Hoshaiah Rabbah",
  "רב (אמורא)": "Abba Arikha",
  "שמואל (אמורא)": "Samuel of Nehardea",
  "רבי יוחנן": "Johanan bar Nappaha",
  "ריש לקיש": "Shimon ben Lakish",
  "רבי יהושע בן לוי": "Joshua ben Levi",
  "רב הונא": "Rav Huna",
  "רב ששת": "Sheshet",
  "רב אסי": "Rav Assi",
  "רב חסדא": "Rav Chisda",
  "רב נחמן": "Rav Nachman",
  "עולא": "Ulla (Talmudist)",
  "מר זוטרא": "Mar Zutra",
  "רבי תנחומא": "Tanhuma bar Abba",
  "רבה בר אבוה": "Rabbah bar Abuha",
  "רמי בר חמא": "Rami bar Hama",
  "רב פפא": "Rav Pappa",
  "רב נחמן בר יצחק": "Rav Nachman bar Yitzchak",
  "רבה בר נחמני": "Rabbah bar Nahmani",
  "אביי": "Abaye",
  "רבא": "Rava (amora)",
  "רב אשי": "Rav Ashi",
  "מר בר רב אשי": "Mar bar Rav Ashi",
  "רבינא": "Ravina I",
  "חנן מאישקיא": "Hanan of Iskiya",
  "רב אחא משבחא": "Ahai of Shabha",
  "יהודאי גאון": "Yehudai ben Nahman",
  "עמרם גאון": "Amram ben Sheshna",
  "רב סעדיה גאון": "Saadia Gaon",
  "נחמיה בן כהן צדק": "Nehemiah ben Kohen Tzedek",
  "רב שרירא גאון": "Sherira ben Hanina",
  "רב האי גאון": "Hai ben Sherira",
  "רבנו גרשום": "Gershom ben Judah",
  "רבנו חננאל": "Chananel ben Chushiel",
  "שמואל הנגיד": "Samuel ibn Naghrillah",
  "שלמה אבן גבירול": "Solomon ibn Gabirol",
  "יצחק אלפסי": "Isaac Alfasi",
  "ר\"י מיגאש": "Joseph ibn Migash",
  "יעקב בן יקר": "Yaakov ben Yakar",
  "רש\"י": "Rashi",
  "נתן מרומי": "Nathan ben Jehiel",
  "בחיי אבן פקודה": "Bahya ibn Paquda",
  "יהודה הלוי": "Judah Halevi",
  "רשב\"ם": "Rashbam",
  "אברהם אבן עזרא": "Abraham ibn Ezra",
  "רבנו תם": "Rabbeinu Tam",
  "ר\"י הזקן": "Isaac ben Samuel",
  "יצחק בן אבא מרי": "Isaac ben Abba Mari",
  "אברהם בן יצחק מנרבונה": "Abraham ben Isaac of Narbonne",
  "אברהם בן דוד מפושקירה": "Abraham ben David",
  "רמב\"ם": "Maimonides",
  "דוד קמחי": "David Kimche",
  "אליעזר בן יואל": "Eliezer ben Joel HaLevi",
  "יהודה החסיד": "Judah ben Samuel of Regensburg",
  "אלעזר מגרמייזא": "Eleazar of Worms",
  "שמשון מקוצי": "Samson of Coucy",
  "יצחק מווינה": "Isaac ben Moses of Vienna",
  "רמב\"ן": "Nachmanides",
  "יונה גירונדי": "Yonah Gerondi",
  "יחיאל מפריז": "Yechiel of Paris",
  "משה מקוצי": "Moses ben Jacob of Coucy",
  "יצחק מקורביל": "Isaac ben Joseph of Corbeil",
  "רבנו פרץ": "Peretz ben Elijah",
  "מהר\"ם מרוטנבורג": "Meir of Rothenburg",
  "שלמה בן אדרת": "Shlomo ibn Aderet",
  "ריטב\"א": "Yom Tov of Seville",
  "מנחם המאירי": "Menachem HaMeiri",
  "אשר בן יחיאל": "Asher ben Jehiel",
  "מרדכי בן הלל": "Mordechai ben Hillel",
  "מאיר הכהן מרוטנבורג": "Meir HaKohen",
  "שמשון בן צדוק": "Samson ben Zadok",
  "רלב\"ג": "Gersonides",
  "יעקב בן אשר": "Jacob ben Asher",
  "ירוחם בן משולם": "Rabbenu Yerucham",
  "אשתורי הפרחי": "Ishtori Haparchi",
  "ר\"ן": "Nissim of Gerona",
  "יצחק בר ששת": "Isaac ben Sheshet",
  "שמעון בן צמח דוראן": "Simeon ben Zemah Duran",
  "יוסף אלבו": "Joseph Albo",
  "יעקב מולין": "Yaakov ben Moshe Levi Moelin",
  "ישראל איסרלן": "Israel Isserlein",
  "יוסף קולון": "Joseph Colon Trabotto",
  "יצחק אברבנאל": "Isaac Abarbanel",
  "עובדיה מברטנורא": "Obadiah of Bertinoro",
  "אברהם זכות": "Abraham Zacuto",
  "יעקב פולק": "Jacob Pollak",
  "יעקב בירב": "Jacob Berab",
  "יוסף קארו": "Joseph Karo",
  "מהר\"ל": "Judah Loew ben Bezalel",
  "משה איסרליש": "Moses Isserles",
  "מרדכי יפה": "Mordecai Yoffe",
  "שלמה לוריא": "Solomon Luria",
  "שמואל אליעזר הלוי איידלס": "Maharsha",
  "יהושע פלק כץ": "Joshua Falk",
  "יום-טוב ליפמן הלר": "Yom-Tov Lipmann Heller",
  "נתן נטע שפירא": "Nathan Nata Spira",
  "שמשון מאוסטרופולי": "Samson ben Pesah Ostropoli",
  "משה אלשיך": "Moshe Alshich",
  "משה קורדובירו": "Moses ben Jacob Cordovero",
  "אלעזר אזכרי": "Elazar ben Moshe Azikri",
  "ישעיה הלוי הורוביץ": "Isaiah Horowitz",
  "בצלאל אשכנזי": "Bezalel Ashkenazi",
  "האר\"י": "Isaac Luria",
  "יואל סירקיש": "Joel Sirkis",
  "דוד הלוי סגל": "David HaLevi Segal",
  "שבתי כהן": "Shabbatai HaKohen",
  "נפתלי כ\"ץ": "Naphtali Cohen",
  "חיים בנבנישתי": "Chaim Benveniste",
  "אליהו הכהן האתמרי": "Elijah ben Solomon Abraham ha-Kohen",
  "אליעזר פאפו": "Eliezer Papo",
  "שמואל קעלין": "Samuel Loew",
  "אברהם אבלי גומבינר": "Avraham Gombiner",
  "יעקב יהושע פלק": "Jacob Joshua Falk",
  "יהודה רוזאניס": "Judah Rosanes",
  "יעקב כולי": "Yaakov Culi",
  "חיים בן עטר": "Chaim ibn Attar",
  "שלום שרעבי": "Shalom Sharabi",
  "חיים יוסף דוד אזולאי": "Chaim Yosef David Azulai",
  "רמח\"ל": "Moshe Chaim Luzzatto",
  "יהונתן אייבשיץ": "Jonathan Eybeschutz",
  "יעקב עמדין": "Jacob Emden",
  "יהודה אשכנזי (טיקטין)": "Judah Ashkenazi",
  "ישראל בעל שם טוב": "Baal Shem Tov",
  "המגיד ממזריטש": "Dov Ber of Mezeritch",
  "יעקב יוסף כ\"ץ": "Jacob Joseph of Polonne",
  "פנחס שפירא מקוריץ": "Pinchas Shapiro of Koretz",
  "לוי יצחק מברדיצ'ב": "Levi Yitzchok of Berditchev",
  "אלימלך מליז'נסק": "Elimelech of Lizhensk",
  "משולם זושא מאניפולי": "Zusha of Hanipol",
  "יחיאל מיכל מזלוטשוב": "Yechiel Michel of Zlotshov",
  "מנחם מנדל מוויטבסק": "Menachem Mendel of Vitebsk",
  "אהרן הגדול מקרלין": "Aharon of Karlin (I)",
  "ישראל הופשטיין מקוז'ניץ": "Yisroel Hopstein",
  "יעקב קרנץ": "Jacob ben Wolf Kranz",
  "יעקב יצחק הורוביץ": "Yaakov Yitzchak of Lublin",
  "אברהם יהושע השיל מאפטא": "Avraham Yehoshua Heshel",
  "מנחם מנדל הגר (קוסוב)": "Menachem Mendel Hager of Kosov",
  "נפתלי צבי הורוביץ": "Naftali Zvi of Ropshitz",
  "צבי הירש מזידיטשוב": "Tzvi Hirsh of Zidichov",
  "שלום רוקח": "Sholom Rokeach",
  "צבי אלימלך שפירא": "Tzvi Elimelech Spira of Dinov",
  "מנחם מנדל מקוצק": "Menachem Mendel of Kotzk",
  "חיים הלברשטאם": "Chaim Halberstam",
  "יצחק מאיר אלתר": "Yitzchak Meir Alter",
  "צדוק הכהן מלובלין": "Zadok HaKohen",
  "אברהם בורנשטיין": "Avrohom Bornsztain",
  "יהודה אריה ליב אלתר": "Yehudah Aryeh Leib Alter",
  "חיים אלעזר שפירא": "Chaim Elazar Spira",
  "יואל טייטלבוים": "Joel Teitelbaum",
  "מנחם מנדל שניאורסון": "Menachem Mendel Schneerson",
  "משה טייטלבוים (ישמח משה)": "Moshe Teitelbaum (Ujhel)",
  "אברהם דנציג": "Avraham Danzig",
  "ישראל פרידמן (רוז'ין)": "Yisrael Friedman of Ruzhin",
  "יעקב יצחק מפשיסחה": "Yaakov Yitzchak of Peshischa",
  "יחזקאל לנדא": "Yechezkel Landau",
  "פנחס הורוביץ": "Pinchas Horowitz",
  "הגאון מווילנה": "Vilna Gaon",
  "חיים מוולוז'ין": "Chaim of Volozhin",
  "שניאור זלמן מלאדי": "Shneur Zalman of Liadi",
  "נחמן מברסלב": "Nachman of Breslov",
  "אריה לייב הלר": "Aryeh Leib Heller",
  "יעקב לורברבוים": "Yaakov Lorberbaum",
  "יוסף באב\"ד": "Joseph Babad",
  "יוסף שאול נתנזון": "Joseph Saul Nathansohn",
  "רש\"ר הירש": "Samson Raphael Hirsch",
  "שלמה קלוגר": "Shlomo Kluger",
  "עקיבא איגר": "Akiva Eiger",
  "אפרים זלמן מרגליות": "Ephraim Zalman Margolioth",
  "חת\"ם סופר": "Moses Sofer",
  "שלמה גאנצפריד": "Shlomo Ganzfried",
  "ישראל ליפקין מסלנט": "Israel Salanter",
  "שמחה זיסל זיו": "Simcha Zissel Ziv",
  "יעקב דוד וילובסקי": "Yaakov Dovid Wilovsky",
  "יוסף יוזל הורוביץ": "Yosef Yozel Horwitz",
  "נתן צבי פינקל": "Nosson Tzvi Finkel (Slabodka)",
  "נפתלי צבי יהודה ברלין": "Naftali Zvi Yehuda Berlin",
  "שמואל סלנט": "Shmuel Salant",
  "משה יהושע יהודה לייב דיסקין": "Yehoshua Leib Diskin",
  "יוסף חיים זוננפלד": "Yosef Chaim Sonnenfeld",
  "חיים הלוי סולובייצ'יק": "Chaim Soloveitchik",
  "שמעון שקופ": "Shimon Shkop",
  "ברוך בר ליבוביץ": "Boruch Ber Leibowitz",
  "יצחק זאב הלוי סולובייצ'יק": "Yitzchok Zev Soloveitchik",
  "יחיאל מיכל הלוי אפשטיין": "Yechiel Michel Epstein",
  "יעקב חיים סופר": "Yaakov Chaim Sofer",
  "יוסף חיים מבגדאד": "Yosef Hayyim",
  "ישראל מאיר הכהן": "Yisrael Meir Kagan",
  "חיים עוזר גרודזנסקי": "Chaim Ozer Grodzinski",
  "מאיר שפירא": "Meir Shapiro",
  "אברהם יצחק הכהן קוק": "Abraham Isaac Kook",
  "איסר זלמן מלצר": "Isser Zalman Meltzer",
  "אברהם ישעיהו קרליץ": "Avrohom Yeshaya Karelitz",
  "יעקב ישראל קניבסקי": "Yaakov Yisrael Kanievsky",
  "משה פיינשטיין": "Moshe Feinstein",
  "אלעזר מנחם מן שך": "Elazar Shach",
  "יוסף שלום אלישיב": "Yosef Shalom Elyashiv",
  "שמואל הלוי ואזנר": "Shmuel Wosner",
  "עובדיה יוסף": "Ovadia Yosef",
  "חורבן בית שני": "Siege of Jerusalem (70 CE)",
  "מצדה": "Masada",
  "מרד בר כוכבא": "Bar Kokhba Revolt",
  "עשרת הרוגי מלכות": "Ten Martyrs",
  "צו מילאנו": "Edict of Milan",
  "ועידת ניקיאה": "First Council of Nicaea",
  "הלל נשיאה": "Hillel II",
  "תלמוד ירושלמי": "Jerusalem Talmud",
  "שקיעת האימפריה הרומית": "Fall of the Western Roman Empire",
  "תלמוד בבלי": "Babylonian Talmud",
  "קורפוס יוריס קיוויליס": "Corpus Juris Civilis",
  "סבוראים": "Savoraim",
  "מוחמד": "Muhammad",
  "הכיבוש הערבי של ארץ ישראל": "Muslim conquest of Syria",
  "הכיבוש המוסלמי של ספרד": "Muslim conquest of the Iberian Peninsula",
  "בגדאד": "Baghdad",
  "ענן בן דוד": "Anan ben David",
  "קרל הגדול": "Charlemagne",
  "ארבעת השבויים": "Four Captive Rabbis",
  "גאונים": "Geonim",
  "רי\"ף": "Isaac Alfasi",
  "מסע הצלב הראשון": "First Crusade",
  "מצור ירושלים (1099)": "Siege of Jerusalem (1099)",
  "אל-מוואחידון": "Almohads",
  "עלילת דם": "Blood libel",
  "עליית בעלי התוספות": "Aliyah of the Tosafists",
  "ועידת לטראנו הרביעית": "Fourth Council of the Lateran",
  "פולמוס הרמב\"ם": "Maimonidean Controversy",
  "ויכוח ברצלונה": "Disputation of Barcelona",
  "גירוש יהודי אנגליה": "Edict of Expulsion",
  "המוות השחור": "Black Death",
  "רנסאנס": "Renaissance",
  "ויכוח טורטוסה": "Disputation of Tortosa",
  "נפילת קונסטנטינופול": "Fall of Constantinople",
  "יוהאן גוטנברג": "Johannes Gutenberg",
  "האינקוויזיציה הספרדית": "Spanish Inquisition",
  "גירוש ספרד": "Expulsion of Jews from Spain",
  "הטבלת יהודי פורטוגל לנצרות": "Persecution of Jews and Muslims by Manuel I of Portugal",
  "גטו ונציה": "Venetian Ghetto",
  "הרפורמציה הפרוטסטנטית": "Reformation",
  "שולחן ערוך": "Shulchan Aruch",
  "ועד ארבע ארצות": "Council of Four Lands",
  "מלחמת שלושים השנים": "Thirty Years' War",
  "גזירות ת\"ח ות\"ט": "Khmelnytsky pogroms",
  "שבתי צבי": "Sabbatai Zevi",
  "קרב וינה": "Battle of Vienna",
  "חסידות": "Hasidic Judaism",
  "המהפכה התעשייתית": "Industrial Revolution",
  "חלוקת פולין": "Partitions of Poland",
  "תנועת ההשכלה היהודית": "Haskalah",
  "המהפכה הצרפתית": "French Revolution",
  "אלסנדרו וולטה": "Alessandro Volta",
  "הסנהדרין של נפוליאון": "Grand Sanhedrin",
  "עלילת דמשק": "Damascus affair",
  "מוצא המינים": "On the Origin of Species",
  "העלייה הראשונה": "First Aliyah",
  "פרשת דרייפוס": "Dreyfus affair",
  "הקונגרס הציוני הראשון": "First Zionist Congress",
  "מלחמת העולם הראשונה": "World War I",
  "הצהרת בלפור": "Balfour Declaration",
  "המהפכה הרוסית": "Russian Revolution (disambiguation)",
  "עליית הנאצים לשלטון": "Nazi seizure of power",
  "השואה": "The Holocaust",
};
